### ISSUE TITLE
Purge BASS Midi

### ISSUE THREAD

**Issue by Salanto** [AttorneyOnline/AO2-Client#1006]
It's barely used, does not work properly with looping and is generally hard to utilise.
File size advantages and negligible compared to stream formats like OPUS

**Comment by collinxchu** [comment]
Should also mention that in some cases, the filesize advantage is actually a _disadvantage_, as storing high quality samples in the .sf2 file can, in shorter songs, actually be worse than just having a properly-compressed .opus file.

**Comment by TrickyLeifa** [comment]
Just remove the others file formats too. Who the hell goes around using XM, IT, S3M, MOD, MTM, UMX and such? They're not even officially listed as being supported.
