### ISSUE TITLE
Issue with very high quality .wav files on qtaudio

### ISSUE THREAD

**Issue by likeawindrammer** [AttorneyOnline/AO2-Client#101]
Found this issue on Layton after the sfx slider was fixed for qtaudio. The issue is, if the sfx sound slider isn't set to 100% then .wav files encoded with a rate higher than what it seems to be 48000hz, then AO will fail to play them completely. But if set to 100% it will play just fine, even layton's .wav files that are encoded with a rate of 192000hz.
So to summarize to trigger this bug you need to: Build AO with qtaudio, have a .wav file encoded with a rate higher than 48000hz and set the sfx slider to anything less than 100%.

**Comment by oldmud0** [comment]
This sounds like a Qt bug.

**Comment by OmniTroid** [comment]
Why in the world do you need 192kHz samples?

**Comment by scatterflower** [comment]
now that qtaudio is gone, this issue is irrelevant
