### ISSUE TITLE
[Feature] Restore Window Position

### ISSUE THREAD

**Issue by Salanto** [AttorneyOnline/AO2-Client#1012]
Currently the client always opens wherever the underlying window system decided to put it, which is suboptiomal for setups with multiple monitors.

The easiest way we could implement it is using this example from Qt : <https://doc.qt.io/qt-6/restoring-geometry.html>
However, we might want to add some extra fluff, such as:
- Options to enable/disable the functionality as a whole or for individual windows
- Add necessary checks to ensure the window does not end up outside the visible display range, like when a laptop is disconnected from a monitor and you open AO2 after
- Maybe style the settings entry a bit less ugly than what we usually do, lol.

**Comment by in1tiate** [comment]
whats with these homies restoring my window position

**Comment by Salanto** [comment]
I would still do it for the three most relevant ones, i.E Lobby, Courtroom and Settings. The rest is probably ignorable for now.

**Comment by stonedDiscord** [comment]
someone is gonna drag AO behind their taskbar on their 720p laptop
