### ISSUE TITLE
[BUG] Unicode symbols are not properly saved/restored from config.ini

### ISSUE THREAD

**Issue by Salanto** [AttorneyOnline/AO2-Client#1014]
Apparently people put unicode symbols into their usernames in client and since the config rewrite it does not appear to work correctly.

**Comment by lambdcalculus** [comment]
Which symbols are causing trouble exactly? Tried some funky characters (including emoji) and they seemed to be working (on Linux, if that matters somehow).

**Comment by Salanto** [comment]
Before saving/loading
![image](https://github.com/user-attachments/assets/cc2e58d4-fa77-452e-a91d-cca1cfa8f436)
After
![image](https://github.com/user-attachments/assets/894092cc-0d72-4fd1-857f-aad78a434e17)

**Comment by lambdcalculus** [comment]
What is actually saved in the config.ini? Just "Magy"?

**Comment by TrickyLeifa** [comment]
This isn't a problem in the current yet-to-be-released version. Or if it isn't, we don't have the proper symbol propagating this issue.
