### ISSUE TITLE
APNG animations not being played on Linux

### ISSUE THREAD

**Issue by likeawindrammer** [AttorneyOnline/AO2-Client#102]
It looks like libqapng.so is being loaded correctly
```
lstat("/usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqapng.so", {st_mode=S_IFREG|0755, st_size=323208, ...}) = 0
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqapng.so", O_RDONLY|O_CLOEXEC) = 12
fcntl(12, F_SETFD, FD_CLOEXEC)          = 0
fstat(12, {st_mode=S_IFREG|0755, st_size=323208, ...}) = 0
fstat(12, {st_mode=S_IFREG|0755, st_size=323208, ...}) = 0
mmap(NULL, 323208, PROT_READ, MAP_SHARED, 12, 0) = 0x7f8154046000
close(12)                               = 0
munmap(0x7f8154046000, 323208)          = 0
```
But APNG animations aren't played on Linux.

**Comment by oldmud0** [comment]
Have you tried the 2.7 client? It has explicit support for APNG.

**Comment by likeawindrammer** [comment]
Tried 2.7 branch and 2.6.2-extra from Crystalwarrior but had the exact same issue on both.
![Captura de pantalla de 2019-09-11 17-52-33](https://user-images.githubusercontent.com/31085911/64743432-28cde380-d4bd-11e9-8bc7-3db20b97ed44.png)

**Comment by likeawindrammer** [comment]
After building qtapng from source and using that one instead of the pre-built version I am able to see animated apng files on AO on the latest build from the gitlab pipeline without any other modifications. as well on the 2.7 and Crystalwarrior's branches. The problem was probably a mismatch between the QT version I have installed and the QT version the plugin was build against. Since I have QT 5.9 from the Ubuntu repository and the pre-built versions are always compiled with the latest QT and GCC.
This means the issue is in the pipeline since qtapng should be build from source instead of using the pre-built.
