### ISSUE TITLE
The "showname_align" setting is not respected when "showname_outline" is enabled [2.11 RC4]

### ISSUE THREAD

**Issue by Samevi** [AttorneyOnline/AO2-Client#1043]
The showname_align setting in courtroom_design.ini is not respected when showname_outline is enabled in courtroom_fonts.ini.

**To reproduce**
1. Check the latest Action as of writing this post with any chatbox that has showname_outline enabled.
2. Note that the showname no longer aligns as set in the courtroom_design.ini.

**Expected behavior**
Outlined shownames should respect alignment calls.

**Screenshots**
Here is the same message sent using the same theme and chatbox in the latest version and the current stable version:
2.11 RC4
![image](https://github.com/user-attachments/assets/ec3b3950-4a0b-4f51-8c19-b3cddd86ecfb)

2.10.1
![image](https://github.com/user-attachments/assets/ea8b52ff-8e9c-44a6-a0e8-10455341715c)

**Version:**
Win11, 2.11 RC4 (Latest Action as of this bug report).

**Additional context**
I'm going to scream

**Comment by stonedDiscord** [comment]
cleartype being different in the text area is really messing with my eyes

**Comment by in1tiate** [comment]
i can tell i'm going to hate this one
