### ISSUE TITLE
Position dropdown sends a command instead of packet

### ISSUE THREAD

**Issue by Parazoid** [AttorneyOnline/AO2-Client#112]
https://github.com/AttorneyOnline/AO2-Client/blob/317fefb031920b017ddb3d759906be92b02b0fc5/src/courtroom.cpp#L3026

This sends the actual /pos command to the server in a packet, instead of assigning the packet in the messages sent by the client. It's extra redundant and causes unnecessary dependency on the server software.

**Comment by Parazoid** [comment]
A side effect of this is that you can't change your position from the dropdown without typing an OOC name.

**Comment by oldmud0** [comment]
yeah i don't use any of those chat command abominations in the refactored version. gosh darn that branch is gonna take a while...

**Comment by Crystalwarrior** [comment]
Fixed in 2.8 by only sending the position during the actual message. Fixes an issue with packet spam if user rapidly scrolls through the dropdown as well.
