### ISSUE TITLE
Spectator button does not appear when switching characters

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#114]
**Expected behavior:** When I click on the "Change character" button, the character list appears, and I can click on the "Spectate" button to release my character and spectate the current room.

**Actual behavior:** When I click on the "Change character" button, the character list appears, but there is no "Spectate" button.

**Cause:** The spectate button's behavior is simply to cancel character selection, and switch to the gameplay window immediately. To mask this, the spectate button is hidden when changing characters.

**Fix:** Choose character ID `-1` when the spectate button is selected.

**Comment by Crystalwarrior** [comment]
Occurs in 2.8
