### ISSUE TITLE
Shout cannot be disabled after changing character

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#116]
**Steps to reproduce:**

1. Activate "Hold it," "Objection," or "Take that" buttons.
2. Change characters.
3. Try to disable the button.
4. Send a message.

**Expected:** The interjection state is either reset, or the button states are restored to their state before the character switch.

**Actual:** The button highlight states are cleared (e.g. the button does not appear highlighted), but the interjection still plays.

**Fix:** When the theme is reloaded, set the button's highlight states to the actual interjection states.

**Comment by oldmud0** [comment]
Not a bug for any official version of AO.

**Comment by Crystalwarrior** [comment]
Must be present in AO2.8, though I didn't confirm.

**Comment by in1tiate** [comment]
Confirmed present in AO2.8, #147 has been rebased to correct the issue there.
