### ISSUE TITLE
Crashes when master server connection fails

### ISSUE THREAD

**Issue by MD-ThorErik** [AttorneyOnline/AO2-Client#12]
When the master server is down and the client is connected to a server in serverlist, there is a segfault.
The client should not depend on the master server to begin with, only the protocol. Even so, it's a segfault and a segfault should never happen no matter what.

```
Master server socket error: "Conexión rechazada" ( QAbstractSocket::ConnectionRefusedError )
[1]    11223 segmentation fault (core dumped)  ./Attorney_Online_remake
```

**Comment by oldmud0** [comment]
Thought I had done the signals/slots for connection error handling correctly. Let me think about a case where a segfault would occur. Maybe the reconnect timer deleted itself. Next time this happens, can you do `gdb ./Attorney_Online_Remake`, type in `run` and then when the error happens, copy and paste the error info for me?

**Comment by MD-ThorErik** [comment]
To force the masterserver to look down I edit the masterserver.txt maybe? Yes I know about gdb.

**Comment by oldmud0** [comment]
There's no masterserver.txt override. Can you try to reproduce the segfault and send me a stack trace?

**Comment by MD-ThorErik** [comment]
But I'd need to cut connection to masterserver. How?

**Comment by oldmud0** [comment]
@MD-ThorErik Sadly, yes, that's exactly what it means...

**Comment by stonedDiscord** [comment]
just pull out the network cable

**Comment by MD-ThorErik** [comment]
@stonedDiscord Well this bug happened while I was connected to a server while the masterserver was down... I'll recompile the client changing the masterserver IP (if I find where it is first).

**Comment by oldmud0** [comment]
@MD-ThorErik Run your build with `-DLOCAL_MS` or uncomment this line: https://github.com/AttorneyOnline/AO2-Client/blob/4eba53ebb2ca83c61af750d18e34de22ae3b5a2d/networkmanager.h#L11

**Comment by stonedDiscord** [comment]
you can use a local server and cut internet connection

**Comment by MD-ThorErik** [comment]
I could replicate it in gdb but I can't tell where the error originated...
The topmost calls are to "QTextEdit::textCursor()" and "AOTextArea::append_error..."

**Comment by MD-ThorErik** [comment]
So it might be a qt5 bug but I couldn't find anything about QTextEdit::textCursor causing segfaults.

**Comment by stonedDiscord** [comment]
i can not observe this behaviour on AO built with Qt 5.10

**Comment by MD-ThorErik** [comment]
I did "iptables -I INPUT -s 104.131.93.82 -j DROP" to prevent fron connecting to masterserver, then connected to a server in the favorites list. Wait a while or try to type something, and the crash happens.

**Comment by MD-ThorErik** [comment]
qmake --version says it's Qt version 5.10.1

**Comment by oldmud0** [comment]
Issue has aged away.
