### ISSUE TITLE
Custom shout selection does not reset after sending message

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#120]
Reported by Initiate via [Discord](https://discordapp.com/channels/278529040497770496/353369729328611330/685809313931067487).

This issue is only tangentially related to #116.

**Steps to reproduce:**

1. Select a character with multiple custom objections.
2. Right-click the custom button and select a shout from the context menu.
3. Send a message with the shout enabled.
4. Left-click the custom button.
5. Send another message.

**Expected result:**

After left-clicking the custom button, the default shout should be used (`custom.gif/custom.wav`).

**Actual result:**

After left-clicking the custom button, the shout used will be the one that was selected in the context menu in step 2. [This makes it impossible to use the default custom shout, since the default custom shout can only be accessed by left-clicking the custom shout button and not via the context menu.]

**Suggested patch:**

`courtroom.cpp`:
```cpp
    case 4:
      if(objection_custom != "")
      {
          ui_vp_objection->play("custom_objections/" + objection_custom, f_char, f_custom_theme, shout_stay_time);
          objection_player->play("custom_objections/" + objection_custom.split('.')[0] + ".wav", f_char, f_custom_theme);
          objection_custom = ""; // <-- add this line
      }
```

**Comment by Parazoid** [comment]
Custom objections have yet to be merged to master.
