### ISSUE TITLE
Double-clicking to connect hangs on 'Loading characters' if done too fast

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#125]
**Steps to reproduce:**

1. Launch the client. Make sure 'public servers' is selected.

2. Double-click any server in the list. (Do not click the server beforehand!)

**Expected result:**
Connection should happen the same way it does when using the 'Connect' button.

**Actual result:**
Loading will inevitably hang on 'Loading characters'. Escape from this state requires the user to 'cancel' the loading process and attempt to connect again.

**Additional details:**
This seems to be linked to the server's player count being fetched, as if one selects the server beforehand and waits for the player count to populate before double-clicking, connection works as expected.

**Possible fix:**
While hacky, a hardcoded delay in the double-click function would likely solve this. Alternatively, (and much more cleanly,) making sure the player count has been fetched before actually connecting is also a likely solution.

**Comment by in1tiate** [comment]
So, as it turns out this is because `on_server_list_doubleclicked` calls `on_server_list_clicked` - which means it gets called twice, since you can't doubleclick without triggering the single-click signal. I'm not positive why that causes this error, but simply removing the call fixes it.

**Comment by oldmud0** [comment]
This is fixed in the ui-files branch, wherein the clicked signal is not used at all.

**Comment by Crystalwarrior** [comment]
> 
> 
> This is fixed in the ui-files branch, wherein the clicked signal is not used at all.

@oldmud0 port it into 2.8 nerd

**Comment by Crystalwarrior** [comment]
reeeeeeeEEEEEEEEEEEEEEEEEEEEEE
