### ISSUE TITLE
Crash after failed double-click attempt

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#126]
**Steps to reproduce:**

1. Follow the steps outlined in #125.

2. When the loading screen hangs, click 'cancel.'

3. In the Lobby menu, click another server in the server list, then click back to the one you attempted to connect to in step 1.

4. Before the player count updates from 'Offline,' connect to the server.

**Expected result:**
Connection should proceed as normal.

**Actual result:**
Connection *appears* to proceed as normal, but client crashes upon trying to load the character selection screen.

**Additional details:**
This issue is intrinsically linked to #125. Fixing that issue will likely fix this one as well.

**Comment by Crystalwarrior** [comment]
Still happens in 2.8

**Comment by Crystalwarrior** [comment]
we didn't fix it :pensive:

**Comment by raidensnake** [comment]
This was patched in https://github.com/AttorneyOnline/AO2-Client/pull/312
