### ISSUE TITLE
Themes not loading

### ISSUE THREAD

**Issue by MD-ThorErik** [AttorneyOnline/AO2-Client#13]
Since 4eba53ebb2ca83c61af750d18e34de22ae3b5a2d custom themes are not displayed properly. The client starts with the default theme and 'reload theme' has to be pressed. After doing that the buttons of the sprites are misaligned.

**Comment by oldmud0** [comment]
After reverting the changes, Omni [forgot to add a line back in...](https://github.com/AttorneyOnline/AO2-Client/compare/403e5b43288dd945ca504d3b0dfeb2757227c879...master#diff-6a0a53bb466bd65d244206db08905eedL60)
