### ISSUE TITLE
'Casing' button and checkbox are ambiguously named

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#135]
I've never seen anyone use these features, and they're always surprised when I tell them about it. This is, I think, because the 'Casing' label on the button and checkbox is ambiguous to the point of being useless. Personally I suggest changing the checkbox label to 'Case Alerts' (as that's what it controls) and the button label to 'Host case' (as that's what it does).

**Comment by Crystalwarrior** [comment]
👍 
My suggestion is to redesign the system entirely to be more versatile for things outside of casing as well, in my experience that usually leads to simpler and better features as a bonus.

**Comment by oldmud0** [comment]
Frankly, I would recommend removing these buttons and having the server provide this functionality instead through its own commands.

**Comment by Crystalwarrior** [comment]
You know at least 1 server is already using it so we can't remove it until we work together with them for a better alternative

**Comment by Salanto** [comment]
Given we delete this feature, this issue would become moot.
