### ISSUE TITLE
Non-ASCII characters are removed from IC messages when using "Rainbow" color.

### ISSUE THREAD

**Issue by likeawindrammer** [AttorneyOnline/AO2-Client#142]
Non-ASCII characters are removed from IC messages when using "Rainbow" color.
If the message contains only Non-ASCII characters then a blank message is send.
Found on 2.6.2 and Master, the issue has probably been there since Rainbow was added.

**Comment by Crystalwarrior** [comment]
Rainbow color is deleted from 2.8, rip
