### ISSUE TITLE
"Lag" with AO 2.7

### ISSUE THREAD

**Issue by likeawindrammer** [AttorneyOnline/AO2-Client#148]
There's 5 people reporting there's lag/freezes while chatting IC on AO 2.7. That's all I know as I haven't been able to confirm this.

![Captura de pantalla de 2020-04-24 16-15-45](https://user-images.githubusercontent.com/31085911/80261423-9c38f580-8647-11ea-82f5-c99869d0bc8d.png)
![Captura de pantalla de 2020-04-24 16-16-32](https://user-images.githubusercontent.com/31085911/80261424-9cd18c00-8647-11ea-8a90-85175b94d782.png)
![Captura de pantalla de 2020-04-24 16-16-55](https://user-images.githubusercontent.com/31085911/80261426-9cd18c00-8647-11ea-8717-f0873433e6b4.png)
![Captura de pantalla de 2020-04-24 16-18-53](https://user-images.githubusercontent.com/31085911/80261429-9cd18c00-8647-11ea-9497-46c2dc04c34f.png)

**Comment by oldmud0** [comment]
Why is this closed? This seems like a serious issue.

**Comment by raidensnake** [comment]
@likeawindrammer @oldmud0 Both @cents02 and I believe it's related to the changes where the IC  text speed was increased causing compatibility issues between different versions of the client causing a potential bottleneck. This does not happen if both clients are the same version however.

**Comment by in1tiate** [comment]
Confirmed by myself and @Iamgoofball to still exist as of time of writing, though issue does not exist in AOV's fork.

**Comment by Iamgoofball** [comment]
I was able to reproduce this with the latest client build as of like, yesterday.

I was unable to reproduce this with the AOV client I homebrewed months ago.

I suspect 1 of 2 things occurred:
1. Something went wrong with the 2.7 feature ports
2. We fucked up some kind of compiler thing in the pipeline.

**Comment by Iamgoofball** [comment]
This is definitely a high priority issue as 10 seconds of objection spamming hard locked my game.

**Comment by oldmud0** [comment]
A moderator was able to reproduce a full hang after 5-10 minutes of play time.

**Comment by cents02** [comment]
Possible [fix ](https://github.com/AttorneyOnline/AO2-Client/commit/04d3e79215ce9fed7bd27290b010c562f296ae71)

**Comment by Crystalwarrior** [comment]
Does this issue exist on 2.8?
