### ISSUE TITLE
Evidence display is incorrectly drawn at 0,0 regardless of viewport location

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#151]
**Steps to reproduce:**
  - Load a theme that uses a viewport located somewhere other than 0,0. Many 'large-screen' themes do this.
  - Make sure that `left_evidence_icon` and `right_evidence_icon` are appropriately located. (Extremely high numbers shouldn't be common here - remember, this is supposed to be relative to the viewport)
  - Present some evidence.

**Expected result:**
The evidence animation and subsequent display should play at the appropriate location relative to the viewport - at no point should it leave the viewport.

**Actual result:**
https://cdn.discordapp.com/attachments/615898062321090581/703863019377262692/unknown.png
As a bonus, should you position the evidence further to the right than the width of the viewport, Phil Swift will pay a visit to the Court Record to demonstrate the power of Flex Tape.
https://cdn.discordapp.com/attachments/353369729328611330/703857310015160390/unknown.png

**Comment by in1tiate** [comment]
This is present in the latest commit from 2.7-rc, and in all post-2.6 builds I can find. It appears many themes affected by this issue have either moved the evidence so far off-screen that it's not displayed at all, or compromised by placing it in the very corner of the viewport.

**Comment by stonedDiscord** [comment]
![aacastsal](https://user-images.githubusercontent.com/10584181/80308567-07153880-87d0-11ea-8d4c-9db2e5963dc4.png)

**Comment by oldmud0** [comment]
Issue still exists in 2.8.

**Comment by Crystalwarrior** [comment]
@oldmud0 Try it with the latest KFO 2x theme, issue doesn't exist on my end

**Comment by in1tiate** [comment]
Can't reproduce in 2.8.
