### ISSUE TITLE
Odd scaling inconsistencies in AO 2.7

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#154]
Up-scaling of assets in 2.7 behaves oddly as of the time of writing.

- Background assets are now scaled with interpolation that causes extreme blurriness. Depending on whether you like the way this looks this may or may not be a regression; 2.6 does not do this.
- Most viewport assets are also scaled this way (e.g. "Testimony" graphic, CE/WT/G/NG splashes, evidence, etc.)
- Characters are *not* scaled this way, leading to a much more pleasant effect when up-scaling pixel art. Except...
- On clicking 'reload theme', changing character, or otherwise calling `enter_courtroom()`, the character on-screen will revert to the blurry scaling until the GIF has fully played - at which point it will suddenly switch back to the pixel scaling as shown in this video: https://youtu.be/Un-TlZq287I

**Comment by oldmud0** [comment]
Sounds like nearest-neighbor filtering needs to be explicitly applied to more widgets.

**Comment by in1tiate** [comment]
AO 2.7 is cancelled, marking invalid and closing
