### ISSUE TITLE
Certain special characters are not correctly displayed as part of ini-defined shownames

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#155]
Known affected characters:
`'é', '°'`

These characters are displayed correctly when entered into the IC name box by the user, but when pulled from the ini will be displayed incorrectly as one or more other characters (often an accented capital A).

An example is below:
https://i.imgur.com/L9you53.png - what the ini looks like
https://i.imgur.com/IrDrKCI.png - how it is displayed in-client

**Comment by oldmud0** [comment]
- What encoding is the INI in?
- What encoding is the client opening it as?
- How does it look when it's sent through the wire?
- How does it look when it's received?

**Comment by in1tiate** [comment]
The ini is encoded as UTF-8 (no BOM). From what I can see, `read_char_ini` does not specify a codec for QSettings to use. It may be possible to fix this by setting the codec to UTF-8, like so:
```cpp
settings.setIniCodec("UTF-8");
```

**Comment by in1tiate** [comment]
Yep, that worked. I'll add it to the other ini reading functions, since none of them have it either.

**Comment by oldmud0** [comment]
I was kind of expecting Qt to know better than to use the system encoding instead of UTF-8... Anyway, that should do it.
