### ISSUE TITLE
Actual user-friendly documentation for all current + new features introduced by 2.8

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#165]
I started these efforts on my KFO github somewhat, but we _seriously_ need this. A lot of awesome and nifty features of AO2 go completely unnoticed simply because nobody documented them.

https://github.com/Crystalwarrior/KFO-Client/wiki

**Comment by oldmud0** [comment]
https://www.dzombak.com/blog/2015/03/Why-use-GitHub-Wikis-.html

In general, we need a user manual. A wiki is useful for technical details that need quick editing and low overhead with commits and pull requests, but a full docs repo would be nice for something we can publish online or export to a PDF.

**Comment by Crystalwarrior** [comment]
> 
> 
> https://www.dzombak.com/blog/2015/03/Why-use-GitHub-Wikis-.html
> 
> In general, we need a user manual. A wiki is useful for technical details that need quick editing and low overhead with commits and pull requests, but a full docs repo would be nice for something we can publish online or export to a PDF.

well shit you convinced me pretty quickly there
Either way, documentation is a must have.

**Comment by Crystalwarrior** [comment]
@oldmud0 Make a checklist of documentation needed to be created?
https://github.com/AttorneyOnline/docs/blob/master/docs/index.md
https://github.com/AttorneyOnline/docs/tree/master/docs

**Comment by oldmud0** [comment]
I think this is mostly done.
