### ISSUE TITLE
[2.8] Using preanim with zoom freezes viewport until next shout on supported servers

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#169]
One of the features that was not properly finished, fixing will require dumpster diving into the chatting logic and figuring out where it freezes and why.

**Comment by Crystalwarrior** [comment]
Only servers that enable "prezoom" will ever encounter this issue, but regardless this is something that needs to be fixed. Call it a bugged feature/failed implementation..

**Comment by scatterflower** [comment]
Note that this PR prevents clients from causing the issue, but they are still susceptible to it if emote_mod of 4 (or anything else invalid for that matter) shows up on the line. Consider adding a check for this in tsu?
