### ISSUE TITLE
[2.8] Looping sfx are interrupted when the same emote is used without preanim

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#170]
That means if you try chatting after playing the looping preanim sound emote, you will interrupt the looping sound. AOV Armie Buff has a separate preanimation to play looping sfx, but wouldn't it be better if no pre simply didn't interrupt the looping sfx if it's the same emote?

**Comment by scatterflower** [comment]
https://github.com/AttorneyOnline/AO2-Client/blob/ec1c95bdb33dd063880c4cb6c3c9c3cf5d0ed454/src/courtroom.cpp#L1939 this is likely the line causing this, but disabling it might have unintended side effects. needs to be investigated further.

**Comment by scatterflower** [comment]
Gonna consider this intended behavior for the time being. Might mess with this later.

**Comment by scatterflower** [comment]
![image](https://user-images.githubusercontent.com/2956568/90345270-e40fce00-dfe4-11ea-86c4-40c0d377da87.png)

**Comment by scatterflower** [comment]
![image](https://user-images.githubusercontent.com/2956568/90345284-f25dea00-dfe4-11ea-8ad2-3e5b6ed10329.png)
