### ISSUE TITLE
[Feature Request 2.8] Allow mutiple timed sfx for pre-animations.

### ISSUE THREAD

**Issue by ghost** [AttorneyOnline/AO2-Client#183]
It would be good to add multiple timed sfx for example with edgeworth's strained pre to allow both the damage and the desk slam to play in the same sequence.

**Comment by oldmud0** [comment]
Valid feature request. Reopening.

**Comment by Iamgoofball** [comment]
this is already possible with framesfx

**Comment by Crystalwarrior** [comment]
Frame sfx basically makes this redundant, agreed with @Iamgoofball
