### ISSUE TITLE
[Bug 2.8] Unable to connect from favorites without clicking on public first.

### ISSUE THREAD

**Issue by raidensnake** [AttorneyOnline/AO2-Client#184]
For some reason whenever you try to click on a server in the favourites it says it's offline and unable to connect. However if you click on a server on the public list when it shows the number of users them switch to the favourites it works. This needs to be sorted out.

**Comment by likeawindrammer** [comment]
I couldn't replicate this.

**Comment by raidensnake** [comment]
@likeawindrammer It affects 2.8 servers if I use this branch. https://github.com/Crystalwarrior/KFO-Server/tree/compatibility/2.8
