### ISSUE TITLE
[Bug 2.8] Invalid order of asset loading for themes and misc/ chatboxes

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#190]
From @in1tiate:
Certain assets will be loaded from the default theme rather than the user's selected theme if they exist in a format higher up the 'pecking order'
As far as I can tell it's APNG > PNG > GIF
which means if themes/default/defense_speedlines.apng exists, and so does themes/users_theme/defense_speedlines.gif
the APNG one will be used
This means if a server distributes a default theme with APNG assets, any theme that wants to use GIF assets will have to have the user remove them from the default theme
This is annoying pls fix

**Comment by likeawindrammer** [comment]
Could you send me a character that is affected by this bug to reproduce this bug?

**Comment by likeawindrammer** [comment]
Confirmed to still be present

**Comment by likeawindrammer** [comment]
https://github.com/AttorneyOnline/AO2-Client/issues/194 is basically a duplicate of this.

**Comment by oldmud0** [comment]
Doesn't seem like it would be fixed by #228.

**Comment by in1tiate** [comment]
Fixed by #302
