### ISSUE TITLE
[Bug 2.8] Music Display button disappears under specific conditions

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#191]
[Bug in full display](https://cdn.discordapp.com/attachments/699638800632119316/734531167742853140/what_is.gif)
As for what those specific conditions are, it seems to be related to Reload Theme in some way. Only animated music display images are affected.

**Comment by likeawindrammer** [comment]
I couldn't reproduce this bug.

**Comment by likeawindrammer** [comment]
According to crystal this can be reproduced by:
1) launch the client with a non-animated music display (KFO 2x)
2) Switch to default theme (animated music list)
3) Observe results

**Comment by likeawindrammer** [comment]
Confirmed
