### ISSUE TITLE
[Bug 2.8] Emojis are not properly parsed

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#192]
[Image](https://cdn.discordapp.com/attachments/353369729328611330/734410069847965736/Code_gT9ACjkSNd.png)
According to @oldmud0:
> those emoji are usually two byte UTF-8 codepoints
I've no idea what that means but might be a clue?????

**Comment by likeawindrammer** [comment]
Those emojis have a null byte somewhere? If so could be related to this https://github.com/AttorneyOnline/tsuserver3/commit/eb9d4ab7cd4c42c4c39720161f3349665474c26a
Which was done to help mitigate https://github.com/AttorneyOnline/AO2-Client/security/advisories/GHSA-7fpc-9xpq-pxq7

**Comment by oldmud0** [comment]
Can confirm that it is going through the wire properly and being printed correctly in hex by the client. Actually, emoji are represented with 4 bytes in UTF-8 - for instance "🤷" (U+1F937 person shrugging) is encoded in UTF-8 as `f0 9f a4 b7`.

Looks like something is not parsing multibyte characters properly in [`Courtroom::filter_ic_text`](https://github.com/AttorneyOnline/AO2-Client/blob/kfo-ao2/src/courtroom.cpp#L2292)...
