### ISSUE TITLE
[2.8] Screenshake button breaks character offset - shunts to origin

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#193]
[here](https://cdn.discordapp.com/attachments/353369729328611330/734371121612193842/0YtbpThhqA.mp4)
the cause is simple, screenshake button blows its load too early before the character even has a chance to set their "intended pos" on-screen
doesn't occur with \s due to its placement in the character animation parser

**Comment by likeawindrammer** [comment]
I could not reproduce this bug on KFO server with https://github.com/AttorneyOnline/AO2-Client/commit/4a0df25c39b429291c77d571dc9e667831b43a89. Compiled with GCC 7.5.0 on Ubuntu 18.04 using QT 5.15.
