### ISSUE TITLE
[Bug 2.8] misc/folder/config.ini colors may be ignored

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#194]
This is due to hardcoded colors I believe. One of my commits might've resolved this issue, this simply needs to be tested on the bleeding edge release...

**Comment by in1tiate** [comment]
Confirmed still present as of [29f0e06](https://github.com/AttorneyOnline/AO2-Client/commit/29f0e06bc80428a753f6c67012637e914fbe295a).

**Comment by in1tiate** [comment]
Bump, this breaks multiple servers' content bases and should really have been fixed _before_ release but too late for that now

**Comment by Crystalwarrior** [comment]
@in1tiate Could've sworn this was fixed. I made good note of it in the development channel and constantly elevated its priority :/

**Comment by Crystalwarrior** [comment]
Bump. Anyone working on this?

**Comment by likeawindrammer** [comment]
> This is due to hardcoded colors I believe.
No, this is due to the client always using the colors from the default theme. Basically another effect of https://github.com/AttorneyOnline/AO2-Client/issues/190
