### ISSUE TITLE
Can't change minimum blip interval

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#214]
As discussed a few weeks ago, a blip sound timer was added to control the minimum duration between blip sound effects and thus make it more faithful to the games. However, it's hardcoded at 60 ms, and it's not possible to change this interval for users who were already accustomed to the faster blip rate.

The reason this becomes annoying for some users is that it essentially forces every other word to skip a blip by default, except when the tick rate is greater than the minimum blip interval. Unintuitively, this overrides the default "blip rate" setting of 1.

Before release, this interval should be configurable such that the blip player can replicate past behavior, even if it is "wrong" or "unfaithful" according to the games (otherwise blip rate should not be configurable at all).

**Comment by Crystalwarrior** [comment]
So long as the "new way" is the default one and is treated like the main supported one, I'm fine with making ear-bleeding blips optional.

**Comment by Crystalwarrior** [comment]
I think this PR has resolved the timings issues and makes this issue no longer a problem, feel free to reopen if you disagree though
https://github.com/AttorneyOnline/AO2-Client/pull/305

**Comment by oldmud0** [comment]
Yeah, I think the reworked blips should make it tolerable for everyone.

**Comment by oldmud0** [comment]
Resolved fully in #438.
