### ISSUE TITLE
[Bug 2.8] When a music track has a single number in the title causing client to change area.

### ISSUE THREAD

**Issue by raidensnake** [AttorneyOnline/AO2-Client#223]
More details referenced here. https://github.com/Crystalwarrior/KFO-Server/issues/4 Unsure if it's a client or server side bug.

**Comment by in1tiate** [comment]
![image](https://user-images.githubusercontent.com/32779090/89368651-ad12f180-d6a1-11ea-9431-a5fc55499c8a.png)
Multiple reports now.

**Comment by oldmud0** [comment]
Server-side bug.
