### ISSUE TITLE
[Bug 2.8.4] OTF-format fonts are incorrectly handled by themes

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#224]
I'm attempting to use OpenType format (.OTF) fonts in a chatbox theme named `misc/ajhd`. Pictured below are `misc/ajhd/courtroom_fonts.ini` and the result of that configuration in the viewport.

![unknown-dBxslIn](https://user-images.githubusercontent.com/32779090/89111759-42eb1a00-d41f-11ea-9e04-ed95d23429a4.png)

[Here](https://user-images.githubusercontent.com/32779090/89111798-aa08ce80-d41f-11ea-918e-acb897270ac8.png) is an image depicting an otherwise identical configuration that instead utilizes a TrueType format (.TTF) font.

Changing the value of `message_font` to the file name of the font in question [causes it to be displayed, though with incorrect character positioning and kerning](https://user-images.githubusercontent.com/32779090/89111818-eb00e300-d41f-11ea-9ed8-9991faad8d6e.png). The same is not true for `showname_font`, which staunchly refuses to use OpenType fonts.

All of the above also applies to proper themes (located in `base/themes`) as well, confirmed via my own tests.

I've attached the two offending fonts as well as a copy of `misc/ajhd` for your perusal.

**Attachment: [ajhd.zip](https://github.com/AttorneyOnline/AO2-Client/files/5011384/ajhd.zip)**

**Comment by oldmud0** [comment]
One hint, perhaps, is that `showname_bold` is set to 1. It could be possible that this causes Qt to look for the "Bold" style of that font family, and if it's not found then it is falling back to some other font.

**Comment by in1tiate** [comment]
Having tried both, neither measure is effective. However, what _was_ effective was the use of [otf2ttf](https://pypi.org/project/otf2ttf/) to convert the offending font to TrueType format. Installing the TrueType conversion instead of the OpenType original causes the client to display the font as normal. This should confirm that the issue is related to the OpenType format specifically.

**Comment by oldmud0** [comment]
Have you tried another OTF?

**Comment by in1tiate** [comment]
I have. Dual Destinies and Spirit of Justice use Suburga 2 Semi-condensed for their dialogue box, which is available online exclusively in OpenType format. The issue occurs with that font as well - I've attached it for your convenience.
[Suburga2SemiCondensed.zip](https://github.com/AttorneyOnline/AO2-Client/files/5025904/Suburga2SemiCondensed.zip)

**Comment by oldmud0** [comment]
I tested it on another font (Myriad Pro) and it seems like only the regular-weighted version loads OK. Any other fonts don't load. So it looks like Qt is registering a font entry for a specific family _and weight_ for OTF. Which means that we may need to expose the full font weight enum in `courtroom_fonts.ini` to support specially weighted OTFs.

Bad rendering is likely due to Qt still using some D-tier font engine by default that was obviously not tuned for OTFs. Don't want to make you switch completely to FreeType, so try adding `-platform direct2d` to the executable arguments. It made a _significant_ improvement in OTF rendering.

**Comment by Crystalwarrior** [comment]
Still present in 2.9?

**Comment by Crystalwarrior** [comment]
@oldmud0 plz

**Comment by in1tiate** [comment]
As irritating as this issue is, a suitable workaround exists in [otf2ttf](https://pypi.org/project/otf2ttf/). Converting an OTF font to TTF before installing it allows AO to use the font normally. This might be a wontfix, assuming Long agrees.

**Comment by oldmud0** [comment]
After tinkering with it, this looks to be a Windows-specific issue. Looks like it can be fixed by setting the QPA plugin to `direct2d`.

**Comment by oldmud0** [comment]
Can't fix awful OTF rendering on Windows, sorry.
