### ISSUE TITLE
Bold option seems to be broken now

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#227]
![huhhg](https://user-images.githubusercontent.com/3470436/89125963-b574fc00-d4ea-11ea-812a-31f8e978ac2a.png)

apparently it's happening on the theme side, doesn't hurt to double-check the misc/ system as well.

**Comment by Crystalwarrior** [comment]
Discovered yesterday:
![eeeeeeeeeeee](https://user-images.githubusercontent.com/3470436/89127532-c7f53280-d4f6-11ea-992f-96053d3270ab.png)

**Comment by in1tiate** [comment]
Confirmed present in release 2.8.4.

**Comment by scatterflower** [comment]
Doesn't seem to be related to misc/ system

**Comment by scatterflower** [comment]
https://github.com/AttorneyOnline/AO2-Client/blame/ec1c95bdb33dd063880c4cb6c3c9c3cf5d0ed454/src/courtroom.cpp#L978 was the culprit

**Comment by scatterflower** [comment]
Fixed in #250
