### ISSUE TITLE
Char.ini realization= seems to be ignored

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#234]
/title, breaks custom realization sounds for characters, needs to be looked into.

**Comment by Lordofdarkn** [comment]
Go to courtroom_sounds.ini and try changing the realization sfx, it wont work. 
[courtroom_sounds.zip](https://github.com/AttorneyOnline/AO2-Client/files/5025253/courtroom_sounds.zip)

Here's how it looks on my end when I tried doing so

**Comment by scatterflower** [comment]
Fixed in #245
