### ISSUE TITLE
More IC log formatting options

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#235]
* Newline option
![newline option pic](https://user-images.githubusercontent.com/3470436/89351731-4995bd80-d6bb-11ea-8046-9b30b3f07b00.png)

* Timestamp option
![timestamp wo newline](https://user-images.githubusercontent.com/3470436/89351727-469acd00-d6bb-11ea-953e-edd78d642d77.png)
![timestamp w newline](https://user-images.githubusercontent.com/3470436/89351721-426eaf80-d6bb-11ea-8deb-565cf9875e62.png)

* Automatically truncate long names option
![truncated name](https://user-images.githubusercontent.com/3470436/89351771-5adeca00-d6bb-11ea-8803-18f86502cc20.png)

Will come up with more later, hmu in comments if you have ideas

**Comment by oldmud0** [comment]
How about the webAO style? This may help a little with conversion of webAO users to desktop.

- Arrows indicate the log direction on join.
 ![Log direction arrow](https://user-images.githubusercontent.com/5247009/89352377-9193f080-d679-11ea-801a-35944c81b39e.png)
- Timestamps are placed only when the minute changes. Timestamps are also right aligned.
![image](https://user-images.githubusercontent.com/5247009/89352407-a3759380-d679-11ea-8400-9ebd5345442a.png)

**Comment by Crystalwarrior** [comment]
> 
> 
> How about the webAO style? This may help a little with conversion of webAO users to desktop.
> 
Aw hell yeah that'd be sick too, let's include all of these as options

**Comment by in1tiate** [comment]
@stonedDiscord DISABLE SMOOTHING ON BITMAPPED FONTS YOU ANIMAL

**Comment by oldmud0** [comment]
> DISABLE SMOOTHING ON BITMAPPED FONTS YOU ANIMAL

You can't on a browser, we've tried this before.
