### ISSUE TITLE
Linux release not compatible with some LTS distros

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#242]
The Linux toolchain is targeting a version of Qt that is too recent for some hyper-stable distros, such as Debian 10 and Ubuntu 18.04. I believe the CI is currently targeting Qt 5.12.1, but we should probably have it target 5.9.5 (this is the version in 18.04; Debian 10 uses 5.11.3).

However, in order to do this, we must also recompile QtApng because the frame delay patch is only as old as 5.12.1. This is very painful, and things would be better if we could use a saner solution like AppImages. But we cannot do that yet due to the limitations of the asset system.

**Comment by raidensnake** [comment]
@oldmud0 Just for confirmation my fork will compile on 5.9.5 and the same build will work on newer  versions of QT regardless of distro.

**Comment by raidensnake** [comment]
my fork of skycoders is qt 5.9.5 compatible. Just needs a working ci to automate it. https://github.com/raidensnake/QtApng.git

**Comment by oldmud0** [comment]
Fixed CI building - will check in later. However, there are other pressing issues with the Linux version.

**Comment by oldmud0** [comment]
Closed in 5e1474fefc6837d3eb1a2449950d4be1371f5be1.
