### ISSUE TITLE
Program does not correctly handle changing audio devices during runtime [Bass Audio]

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#257]
> when you have headphones on, and remove the headphones the music is muted
> Or how if you put in headphones the audio of ao will come through speakers anyway.

Basically, if the audio devices change after startup in any way, AO2 will not react or care in any way despite BASS providing relevant hooks for just that happening.

Fix this due to 2.8.5 and we will make a lot of returning old users very happy.

**Comment by scatterflower** [comment]
the audio device selection does not seem to be functional at all
