### ISSUE TITLE
Qt audio backend is broken on Linux

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#263]
The Linux release did not really undergo a whole lot of testing, and it suffered likewise.

After I fixed the CI, the Linux version would simply crash upon joining a server due to the Qt Multimedia backend not exhibiting the same behavior as the BASS backend that was changed in 2.8. So I fixed that, but then there were more problems yet:

- Opus sound effects/blips can't be loaded with `QSoundEffect` because [`QSoundEffect` only supports WAV](https://code.woboq.org/qt5/qtmultimedia/src/multimedia/audio/qsoundeffect_pulse_p.cpp.html#_ZN19QSoundEffectPrivate18supportedMimeTypesEv). So we have to change blips to WAV, and make other SFX use the regular audio player instead.
- A-B loop support was never written.
- Other functionality implemented relies on calls to BASS-exclusive functions that don't have a 1:1 match with Qt Multimedia.

There are only two real options here:

1. Keep pushing through with Qt Multimedia, for the sake of open-source, since BASS is our only nonfree dependency.
2. Abandon Qt Multimedia, and start using BASS as the exclusive audio engine again.

**Comment by scatterflower** [comment]
I say scrap it. BASS works, so use BASS.

**Comment by stonedDiscord** [comment]
i know the mac version crashes for me when built with qtmultimedia because my VM has no audio device.

**Comment by oldmud0** [comment]
Resolved in https://github.com/AttorneyOnline/AO2-Client/commit/9eb0f53db1ae87058458eae267f2a72e3a0a8091. Qt Multimedia was dropped.

**Comment by stonedDiscord** [comment]
https://twitchy.com/wp-content/uploads/2016/05/bernie-sanders-sad.jpg
