### ISSUE TITLE
Logs should be named in a sort-friendly format

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#265]
A user reported that the log format is not very conducive to sorting by name, despite sorting by date being the correct solution. The log naming format should be changed to something like `YYYY-MM-DD HH-MM-SS.log` to make it easier to sort by name, which is the default sorting order for most file managers.

**Comment by scatterflower** [comment]
just tell them to sort by date smh

**Comment by oldmud0** [comment]
I did, but the user wants the name to be nicer - otherwise the name is pointless and might as well be a string of numbers.

**Comment by newaccountnewlife** [comment]
Just use some text processing tools to rearrange it, e.g. awk, to rename the files. This of course is a temporary solution, but it's \orth a try
