### ISSUE TITLE
[2.8.5] Pressing "Save" in the Options GUI interrupts music and sounds

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#269]
Caused by audio devices changing every time you save regardless if the audio device config actually changed.
Solution must check if the user actually has interacted with the Audio Device dropdown list in any way, and only update the audio device if that's true.

**Comment by stonedDiscord** [comment]
https://github.com/AttorneyOnline/AO2-Client/blob/master/src/aooptionsdialog.cpp#L812

what does this do then???

**Comment by stonedDiscord** [comment]
wait no this is fixed
