### ISSUE TITLE
"on" button generator doesn't darken icon if source image is indexed

### ISSUE THREAD

**Issue by likeawindrammer** [AttorneyOnline/AO2-Client#273]
https://github.com/AttorneyOnline/AO2-Client/pull/201 Will generate an "on" button looking exactly the same as the source "off" button if it's indexed.
Just like the documentation of [qimage](https://doc.qt.io/qt-5/qimage.html) says:
> Warning: Painting on a QImage with the format QImage::Format_Indexed8 is not supported.

**Comment by oldmud0** [comment]
So how do we know if a QImage is paintable?

**Comment by likeawindrammer** [comment]
> So how do we know if a QImage is paintable?

I was thinking of just converting the image to RGBA on memory for the off button.
@oldmud0 pls review https://github.com/AttorneyOnline/AO2-Client/pull/274
