### ISSUE TITLE
[BUG 2.8.5] Unexpected loop glitch on initial load of animated backgrounds.

### ISSUE THREAD

**Issue by ghost** [AttorneyOnline/AO2-Client#281]
For some unknown reason on the initial connect of an animated background the background unexpectedly glitches out. it corrects itself after you lave and rejoin an area.

Demonstration:
![bug](https://user-images.githubusercontent.com/1094029/91835675-9d0b1500-ec41-11ea-850c-ce7d88ea46bb.gif)

**Comment by stonedDiscord** [comment]
looks like qt scaling the first frame of the animation different from the others

**Comment by raidensnake** [comment]
the funny part is all the frames are the same it only does it when you first load it.

**Comment by raidensnake** [comment]
@stonedDiscord @Crystalwarrior I confirmed this caching is the root cause.

**Comment by raidensnake** [comment]
From what it looks like it's not caching the first frame properly.

**Comment by Crystalwarrior** [comment]
I SURE DO FUCKING LOVE QMOVIE, DON'T YOU LOVE QMOVIE??? I FUCKING LOVE IT!!!!!!!!

**Comment by Crystalwarrior** [comment]
gotta use AOImageReader for AOScene same way characters use it

**Comment by raidensnake** [comment]
the caching works great. just needs tweaking to fix that issue.

**Comment by oldmud0** [comment]
Actually, the first frame is being loaded correctly. The rest are being loaded wrong. The correct strategy is nearest-neighbor filtering, but this is not being applied.

**Comment by raidensnake** [comment]
the first frame seems to glitch out though.

**Comment by Crystalwarrior** [comment]
the first frame is correct, the rest is fucked

**Comment by Crystalwarrior** [comment]
> Animated BG is stretching every time an emote is posted.
> bg was kinda widescreen


btw assign yourself whoever wants to fix this

**Comment by in1tiate** [comment]
unsure why this was closed

**Comment by raidensnake** [comment]
no longer being maintained.

**Comment by in1tiate** [comment]
what are you talking about, the pull request that fixes this issue is absolutely still being maintained
