### ISSUE TITLE
Effects.ini can escape to file structure.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#284]
Sanitize your inputs ree.
To accomplish, define an effect such as "../../../characters/Maya/(a)mayanormal.apng = 1" in the effects.ini.

Proposed solution: Don't let effects.ini escape above the effects folder thanks.

**Comment by in1tiate** [comment]
Casting my ballot to flag this 'wontfix'. While occasionally annoying, escaping to other elements has seen use in servers' filebases since 2.6. If there's a security concern, the only thing that should actually be done is to make sure user paths cannot escape the executable's directory.

**Comment by Crystalwarrior** [comment]
Sanitizing it so you can never escape beyond the folder where the .exe is sounds like the most sensible solution

**Comment by Iamgoofball** [comment]
@collinxchu You'd be hard pressed to find an actual security flaw here unless you already got a user to install suspicious files, which at that point whether or not you can display arbitrary images is not a concern

**Comment by scatterflower** [comment]
imo this is a wontfix
