### ISSUE TITLE
Looping effects cover the text box.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#286]
Once again limiting the usefulness of effects, any effect will cover the text box and text crawl, obscuring it entirely. Layering issue more than anything.

**Comment by collinxchu** [comment]
Here's an example. Just drop it in your default/themes folder (it'll replace the existing effects.ini so be careful). Then use the autism effect while typing, and you'll see it covers the text box.

[Link](https://www.dropbox.com/s/5vdod9dd8tboxl1/effects.rar?dl=0)

**Comment by collinxchu** [comment]
Screenshot for posterity: [Link](https://i.imgur.com/tByg8cV.png)

**Comment by oldmud0** [comment]
I think this is intended behavior to make the flash effect more authentic.

**Comment by collinxchu** [comment]
Well shit. If it's intended then I can't really do anything about it. Unfortunate for what I'd like to use it for but can't be helped.

**Comment by Crystalwarrior** [comment]
Effects system should utilize the effects.ini more to be able to fine-tune if the effect appears in front of the chat box, behind the chat box or behind the character.

**Comment by oldmud0** [comment]
Oh dear.
