### ISSUE TITLE
It's far too easy to accidentally send a blank post when sending short messages.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#287]
To reproduce: Hold enter for a short period after sending a short message. It will be followed up by a blank post.
Solution: Either limit the rate of sent messages on the tsuserver end or on the client end.

I accidentally do this all the time post-update and it's infuriating.

**Comment by collinxchu** [comment]
It happens unintentionally to me quite often. I use a mechanical keyboard which has a long travel time, for instance. I'm not certain blaming users for this behavior is the right solution.

**Comment by in1tiate** [comment]
Mm, apologies, I misunderstood the issue. A clientside ratelimit on messages sent sounds like a decent idea, even just half a second would suffice to stop accidental doubleposting or blanking.

**Comment by oldmud0** [comment]
600 ms timer should work well to block the enter signal.
