### ISSUE TITLE
Enabling the log newline option changes how the log is printed in a janky way.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#288]
Instead of printing single lines it collapses posts into a heading under a name (and only one blankpost total) - but only after reloading theme. Until then it'll print in the old fashion (and still again only one blankpost total).

Solution: Don't change the log's format based on whether or not I want to see if someone's blankposts REEEEE.

**Comment by in1tiate** [comment]
Invalid, all log style changes take no effect until "reload theme" is used.
