### ISSUE TITLE
SHUT THE FUCK UP JUMBLES

### ISSUE THREAD

**Issue by ghost** [AttorneyOnline/AO2-Client#289]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE I DON'T LIKE PATHFINDING AND FUN WHAT ABOUT MY QUALITY CASES **_REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE_**

In short: Shut the fuck up and enjoy the possibilities this can give to both casing and RP

**Comment by raidensnake** [comment]
If you are asking for help don't spam post issues.
