### ISSUE TITLE
I am a fucking retard that must compulsively hit enter twice

### ISSUE THREAD

**Issue by ghost** [AttorneyOnline/AO2-Client#291]
I don't like the enter blankpost feature because I'm a fucking autist who has to press enter five times either by french internet or my massive retardation. Please kindly remove the feature and let me logspam spaces as thing I don't like is unsanitized and dumb and fun is not allowed please remove features I don't like. I will proceed to spam this entire github with my bug reports as I am the number one bug finder and content creator, look at how big my cock is.

**Comment by raidensnake** [comment]
I seriously doubt that for a start. Also if you want some help there's no need to be soo rude. Show some respect.
