### ISSUE TITLE
Reloading theme makes "X" buttons on iniswaps dropdown vanish.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#293]
Not sure what specifically causes this behavior, but to reproduce: Have anything but the default selected on the iniswaps dropdown, then reload theme. The X to delete that particular iniswap will vanish.

No idea what could be done to fix it as I'm not overly familiar with how reloading theme works.

**Comment by in1tiate** [comment]
Logic error, reloading theme resets all theme elements but fails to correctly set this particular element when it's needed because the function to do so is not called by `set_widgets()`.
