### ISSUE TITLE
Double clicking a song category stops music AND collapses/expands it.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#294]
Just a bit janky. Should probably just stop the music since there's already a button immediately to the left that does the same thing, and can be annoying when just trying to stop the music as you may need to then expand the category again.

**Comment by oldmud0** [comment]
I am going to untag this as a bug because double-clicking on items expanding and collapsing their children is a feature built into Qt (and common for tree view implementations). It would probably be more intuitive to have the opposite behavior - do not send track changes when double-clicking categories.

**Comment by collinxchu** [comment]
Well, you'd have to add some way to kill the music that wasn't using categories if that's the case. Otherwise every server would have to add a dummy track.

**Comment by in1tiate** [comment]
Wouldn't a dedicated "stop music" entry in the context menu work for this?

**Comment by collinxchu** [comment]
That would be best - especially if you can preserve things like the 'fade out' function.

**Comment by in1tiate** [comment]
The easiest but perhaps not the cleanest solution is to have a dedicated "stop music" entry that simply sends a "play song" packet containing a song that does not exist, the obvious issue being that if one were to create it the client would play it instead of stopping the music.

**Comment by collinxchu** [comment]
That's what I was referring to with the "dummy track" thing. Some servers use 1.mp3 as their "stop music" ghetto method.

**Comment by oldmud0** [comment]
Traditionally, there has always been a track called `~stop.mp3`.
