### ISSUE TITLE
The default theme's "Custom" button encroaches on the IC log.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#296]
Makes the game LITERALLY unplayable.
Pictured here: [Link](https://i.imgur.com/J8EFvPz.png)
Solution: Make it like the AceAttorney theme where the log stops short of the space the button fills like so: [Link](https://i.imgur.com/zcoXTVU.png)

**Comment by in1tiate** [comment]
Invalid. All theme issues should be directed to https://github.com/AttorneyOnline/AO2-Themes.
