### ISSUE TITLE
Proper moderation tools instead of relying on OOC commands

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#297]
These would include:

- An easy way to determine a user's IPID
- An actual moderator GUI interface, allowing for kicks, bans, etc
- A way to log in without requiring the use of an OOC command

**Comment by Iamgoofball** [comment]
this was on my todo list at aov before Qt burned me out

**Comment by dmcnvbgfgh-cancer** [comment]
> An easy way to determine a user's IPID

thinking of maybe a little window in the corner of the viewport for IC messages that shows the IPID?

> A way to log in without requiring the use of an OOC command

with proper authentication, preferably

**Comment by in1tiate** [comment]
Addressed by https://github.com/AttorneyOnline/AO2-Client/pull/996
