### ISSUE TITLE
Webp files not rendering properly.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#303]
Unsure of what is causing it, but frames are not being disposed of properly when using .webp files, as shown in: [LINK](https://www.dropbox.com/s/983hrzyjpsab6s8/NyXtE1WMWC.mp4?dl=0)

The file in question renders just fine in every other program I've used to troubleshoot the issue. I've uploaded it here: [LINK](https://www.dropbox.com/s/5xajcom7pxw90i9/%28a%29normal.webp?dl=0) for examination. I've tried exporting directly to webp from aseprite, converting from individual frames, and so on. This issue does not exist for .apng or .gif versions of this particular image.

**Comment by oldmud0** [comment]
With `webpinfo` all of the `ANMF` chunks appear to have `Dispose: 0` and `Blend: 1`. Does this occur for *all* WebP files, not just those authored by you or your team? Does this occur for lossy (VP8) animations as well, not just for lossless (VP8L) animations?

**Comment by collinxchu** [comment]
Same behavior regardless of whether it's lossy or lossless.
Here's a copy of the lossy version if you want to take a look: [LINK](https://www.dropbox.com/s/qdu6dckb0k9hq0l/lossy.webp?dl=0)

Also happens to other webp files I've gotten from other locations after some brief testing - notably this one: [Link](https://www.dropbox.com/s/ct7naswt6usxvfv/kirigiri.webp?dl=0)

I can test other webp files if provided, mind you.

**Comment by newaccountnewlife** [comment]
This seems like an issue with the WebP decoder, though I have no idea what causes this.

**Comment by k-emiko** [comment]
Can confirm. Happens to me on linux, but my windows buddy also has this problem.
Happens with almost all webps, here's one example. [normal.webp.zip](https://github.com/AttorneyOnline/AO2-Client/files/5635494/normal.webp.zip)
Does not happen with this [An1.webp.zip](https://github.com/AttorneyOnline/AO2-Client/files/5635513/An1.webp.zip)
The matrix anim was assembled using [google's webpmux](https://developers.google.com/speed/webp/docs/webpmux)
I found that adding frames like this gets rid of the trailing frames in the viewport:
`-frame 00001.webp +25+0+0+1-b`
As far as I understand, I'm actually telling webpmux to leave the frames as background (last "+1:), but it does make client dispose of the frames properly.
Hope this helps you guys find the cause for this.

**Comment by in1tiate** [comment]
This is caused by building using a Qt version below 5.14. Versions at or above 5.14 render webps correctly.

**Comment by in1tiate** [comment]
Still present in `2.9.0-rc1`.

**Comment by oldmud0** [comment]
Might need to rebuild the Windows build container. Sigh.

**Comment by in1tiate** [comment]
Resolved as of 2.9.0-rc2.
