### ISSUE TITLE
"has played a song" IC log message uses character folder name instead of showname

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#304]
![изображение](https://user-images.githubusercontent.com/3470436/92791751-9b65ed80-f3b5-11ea-976f-fadd4c9a7050.png)
Works with custom shownames

**Comment by in1tiate** [comment]
![image](https://user-images.githubusercontent.com/32779090/92981987-f9e8a580-f461-11ea-8857-71b8b0f27e3d.png)
seems legit
