### ISSUE TITLE
Iniswapping/changing character resets the position dropdown

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#308]
Position dropdown should remain untouched from your chosen setting when you change character or iniswap, the default position should only kick in if there's no position set in general

**Comment by Crystalwarrior** [comment]
Actually if we made this a setting that would solve both problems at once

**Comment by oldmud0** [comment]
How do you know if the position was unset?

**Comment by Crystalwarrior** [comment]
@oldmud0 it's not set when you first join

**Comment by oldmud0** [comment]
How do you "unset" your position after you set it?

**Comment by in1tiate** [comment]
A possible way of doing this is by reusing the "X" button logic we use for iniswaps and sounds - when the user selects a position from the dropdown, we save that position in a different variable that has priority over the character's default position. An "X" button will appear next to the dropdown that, when clicked, clears that variable and resets the position to whatever the character's default is.

**Comment by oldmud0** [comment]
Or, perhaps make an option named `Default ([pos])`?
