### ISSUE TITLE
Adjusting music volume mid fade-out/fade-in does not apply properly.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#310]
To reproduce, enable fade out, fade in, or both, and switch from one song to the other. While the fade is still happening, adjust the music volume.

For fade-out only, the volume of the new song is adjusted but the one currently fading out does not get adjusted.
For fade-in only and fade-out + fade-in, the music volume is not applied if the volume is not adjusted a second time after the fade-in is complete.

**Comment by oldmud0** [comment]
> For fade-out only, the volume of the new song is adjusted but the one currently fading out does not get adjusted.

Seems fine. Won't fix.

>  For fade-in only and fade-out + fade-in, the music volume is not applied if the volume is not adjusted a second time after the fade-in is complete.

Eh. Looks like [`ChannelSlideAttribute`](https://www.un4seen.com/doc/#bass/BASS_ChannelSlideAttribute.html) overrides all `ChannelSetAttribute` calls while the slide is taking effect... maybe when setting up the fade in, hook onto the `BASS_SYNC_SLIDE` event to cause another brief slide that sets it to the most recently set volume.

**Comment by collinxchu** [comment]
You could also physically lock the slider until the fade is done, if that's possible. I'm not sure how easy to implement that would be.

**Comment by oldmud0** [comment]
I think if you're dragging the slider while the slider is disabled, it'll do something funny.
