### ISSUE TITLE
[Feature Request 2.8] Add protocol for generic pop-up window

### ISSUE THREAD

**Issue by LawfulDickish** [AttorneyOnline/AO2-Client#315]
Currently, pop-ups are hard coded to only show up on kick and ban messages, with the accompanying procedures linked to them. What is desired is the ability to just send a client a pop-up window that just displays the given text to allow server software greater freedom in its use, specifically for things like moderator messages to replace mod-only red-text as a clearly visible interaction with a user from server staff.

**Comment by newaccountnewlife** [comment]
This sounds great on paper, however, there's 2 major issues with it, being the fact that

**Comment by oldmud0** [comment]
There's a lot of RPC groundwork that has to be laid down for a native serverside UI to work at least somewhat consistently. Otherwise it would have to be a web engine UI.

**Comment by stonedDiscord** [comment]
this is the client repo, we don't care about the server here
he is talking about the MessageBox you get when you're kicked

**Comment by oldmud0** [comment]
Oh, I assumed he was talking about a gosh darn freeform dialog box with any number of widgets. But modal dialogs are still rather annoying because spacebar can dismiss them (e.g. while typing).
