### ISSUE TITLE
[2.8.6] demo playback system

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#317]
This is extremely important as we need a way to actually archive this shit we're doing, otherwise if the program dies for whatever reason a lot of our experiences will just be lost to the nether, and the recordings are annoying as hell to edit and trim out dead air due to how music+blips work.

Here's how the file itself would be formatted in theory, with tab characters separating packets:
```
# 0	'MS' IC message
0	time	msg_type	pre	folder	anim	msg	pos	sfx	emote_mod	cid	sfx_delay	button	evidence	flip	ding	color	showname	charid_pair	other_folder	other_emote	offset_pair	other_offset	other_flip	nonint_pre	sfx_looping	screenshake	frames_shake	frames_realization	frames_sfx	additive	effect
# 1	'RT' Judge Buttons
1	time	sign	type
# 2	'BN' Background Change
2	time	background	pos
# 3	'SP' Pos change
3	pos
# 4	'MC' Music
4	time	name	cid	showname	loop	channel	effects
# 5	'HP' Penalty Bar
5	time	side	value
# 6	'CT' OOC message
6	time	name	message
```

"time" is miliseconds passed since the first recorded entry. First recorded entry will always have "time" set to 0.
Playback can be organized in-client, or using a separate program - the latter would take more work and I advise against it, just use what's fuckin there already and save us all the hassle `:^)`

**Comment by Crystalwarrior** [comment]
Oh yeah, once this is done you can also theoretically implement a macro system if you wanted to later for those GM cutscenes and other bullshit.

**Comment by stonedDiscord** [comment]
AO1 used network logs with "wait#" commands in between.
It's a much simpler format and you can implement it by directly piping the file into AOs network handlers
