### ISSUE TITLE
For whatever ungodly reason, this specific opus sfx just fucking refuses to play.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#327]
I have absolutely no idea what the hell is causing this. It's a valid opus file, it plays fine outside of the client, and the ini is pointing to this correctly, but no it just doesn't want to play in-client at all fucking christ AAAAAAAAAAA

Confirmed by a few of us in the AOV content testing circlejerk.

https://www.dropbox.com/s/3plgdjcqt0l26dv/dgs2-slash.opus?dl=0

To reproduce: Use this cursed .opus file in a char_ini and try and use it.

**Comment by in1tiate** [comment]
![image](https://user-images.githubusercontent.com/32779090/96432668-9ec97180-11ca-11eb-86b0-99a45bc8a3e3.png)
This is a PCM WAVE file, not an Opus-encoded file. Rename the extension to .wav.

**Comment by collinxchu** [comment]
Oh for fuck's sake this autist
