### ISSUE TITLE
Linux client fails to display webp

### ISSUE THREAD

**Issue by k-emiko** [AttorneyOnline/AO2-Client#330]
Exactly what the title says.
Terminal output when the crash happens:

> QPixmap::scaleHeight: Pixmap is a null pixmap
> Segmentation fault (core dumped)

Experienced on LMDE and latest version of the client (2.8.5 with hotfix).

**Comment by newaccountnewlife** [comment]
Please send the file that caused the issue for reproduction.
Segfaults are rather common with the client, so I wouldn't assume that the root cause would be rendering webp.
AO is still very new to WebP though, despite it already being around for a decade, so it wouldn't really surprise me. Did you check that WebP decoding is actually the issue, since `QPixmap::scaleHeight: Pixmap is a null pixmap` is a very common error?

**Comment by newaccountnewlife** [comment]
also try another libwebp

**Comment by k-emiko** [comment]
@newaccountnewlife 
Here is a couple of files I have problems with: [mm.zip](https://github.com/AttorneyOnline/AO2-Client/files/5426841/mm.zip)
The crashes happened as soon as I'd hit the Enter key for sending a webp emote, I'm not sure I can assume anything else since I'm not familiar with client's inner workings.
Although now that I've installed the webp package, the client stopped crashing: it just doesn't show anything where a webp is supposed to be and the terminal keeps spamming the `null pixmap` message. I'm not sure what's exactly is going on with that since I tried purging the webp package after that and the crashes did not return. So I'll revise the issue name.
Can you give me a couple of pointers to where/how to try another libwebp?

**Comment by raidensnake** [comment]
@k-emiko can you confirm what distro you're using?

**Comment by k-emiko** [comment]
@raidensnake LMDE 4 Debbie

**Comment by raidensnake** [comment]
oh you mean linux mint debian edition. I think I know what is going on. You seem to be missing a package needed for AO. You need to open a terminal and run the command `sudo apt-get install qt5-image-formats-plugins` to install the webp plugin.

**Comment by k-emiko** [comment]
@raidensnake *facepalm* that did help, thank you!
Imma close this now.

**Comment by newaccountnewlife** [comment]
This should probably be FAQ'd.

**Comment by oldmud0** [comment]
I'm going to note that package name. I've never seen that package before.

**Comment by raidensnake** [comment]
That's the debian/ubuntu package name.
