### ISSUE TITLE
[Feature Request] Add audio streaming (was present in AO1.8)

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#336]
![lol](https://user-images.githubusercontent.com/3470436/98566427-ca1e1880-22bf-11eb-82ea-b51c30d5ffea.png)

**Comment by raidensnake** [comment]
Support was added with bass and an implementation was added but it didn't work for some reason.

**Comment by raidensnake** [comment]
@Crystalwarrior Support was added with bass and an implementation was added but it didn't work for some reason.
A merge for the implementation was made here https://github.com/AttorneyOnline/AO2-Client/pull/134

**Comment by oldmud0** [comment]
Because it got trampled over and removed during the 2.8 merging process.

**Comment by raidensnake** [comment]
It looks like it would need adjusting for 2.8.

**Comment by raidensnake** [comment]
added a patch that has been tested and confirmed working.
