### ISSUE TITLE
Loading case INIs fails to load casedocs with urls containing "#"

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#347]
![image](https://user-images.githubusercontent.com/32779090/100659351-2354f700-3316-11eb-9d2e-03e4700cadf9.png)

The above image shows an example of a case INI that causes this issue. This is due to the packet separator character being "#," causing the extra # to be interpreted as an additional parameter. Tsuserver interprets this as a malformed packet and throws it out, so the casedoc is never set.

Solution: Properly sanitize user input.

**Comment by stonedDiscord** [comment]
https://github.com/AttorneyOnline/AO2-Client/blob/master/src/aopacket.cpp#L36
<num>
