### ISSUE TITLE
Evidence loaded via case INI is loaded in lexographical order instead of numerical

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#348]
For example, a case with 11 pieces of evidence will incorrectly load them in the order [1, 10, 11, 2, 3, 4, 5, 6, 7, 8, 9].

**Comment by oldmud0** [comment]
[`QSettings::childGroups`](https://code.woboq.org/qt5/qtbase/src/corelib/io/qsettings.cpp.html#1340) sorts children lexicographically. You gotta resort it in numerical order.

**Comment by in1tiate** [comment]
Undocumented Qt Jank™️ strikes again, I see.
