### ISSUE TITLE
Audio fading out is audible even when audio is set to 0%

### ISSUE THREAD

**Issue by Salanto** [AttorneyOnline/AO2-Client#349]
Tested with the 2.8.5 Client.

Steps to reproduce ;

1. Join a server and play a song
2. Set audio to 0% using the slider or the settings menu
3. Play another song

The fading out audio can be heard at a low volume.

**Comment by collinxchu** [comment]
Might be the same issues as https://github.com/AttorneyOnline/AO2-Client/issues/310

**Comment by oldmud0** [comment]
This one's slightly different from #310 since the bar is not being touched during the fade.
