### ISSUE TITLE
Make BASS support optional

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#35]
Audio support should be a choice of either BASS or Qt Multimedia.

BASS should be used for Windows, since Opus support would require installing Media Foundation codecs.
Qt Multimedia should be used for Linux, since audio _should_ go through GStreamer which already supports practically anything, and we don't want to depend on a nonfree library.

**Comment by stonedDiscord** [comment]
https://github.com/AttorneyOnline/AO2-Client/tree/bass-optional

**Comment by oldmud0** [comment]
Closed: https://gitlab.com/AttorneyOnline/AO2-Client/issues/35
