### ISSUE TITLE
Client looping fails when the container is .opus file

### ISSUE THREAD

**Issue by kibadimundi** [AttorneyOnline/AO2-Client#357]
Hi. I tried to make client looping with loop_start and loop_end. It works nice with ogg and mp3, but with opus files it fails.  It's always looping from sample 0 to last sample of the file.

But when you change the extension (with no reencoding, just renaming the file) to ogg, it works like it's suposed to.

**Comment by collinxchu** [comment]
We on AOV actively use only opus and loop points successfully. There's probably another factor at play.

**Comment by kibadimundi** [comment]
Well. I reencodec the song selecting libopus on Audacity and now just works. I don't understand what happened. Anyway, I close this

**Comment by oldmud0** [comment]
What encoder did you use previously?

**Comment by kibadimundi** [comment]
I used the default export to opus in Audacity with 32kbps for bitrate, and the sample rate was 41.1Khz, but I configured Audacity on 48Khz for calculate the samples. Maybe I didn't take the samples at 48Khz, who knows
