### ISSUE TITLE
Characters unable to pair with eachother if char.ini's are in a subfolder.

### ISSUE THREAD

**Issue by Nahyuta** [AttorneyOnline/AO2-Client#358]
There is an issue that if you try to pair with someone that uses a character set within a subfolder the character pairing seems to get ignored.

Example:

If these 2 were to pair with each other it works.
Miles/char.ini
Franziska/char.ini

However if one character or both use subfolders like the examples below:

Ema/Witness/char.ini
Ini/char.ini

or 

Amara/Nayna/char.ini
Eve/Prosecutor/char.ini

Neither can pair with eachother as the either the client or server seems to ignore them.

**Comment by oldmud0** [comment]
That's not a supported configuration. Do not attempt to place more than one character in a folder.

**Comment by Nahyuta** [comment]
Sorry for the confusion but they're not different characters, They're the iniswaps for the same character to better organise them. Other servers already do this as well,

**Comment by oldmud0** [comment]
So, you can't pair with the same CID as yourself. When you enter the pair menu, what are you selecting?

**Comment by Nahyuta** [comment]
In this example:

Ema/char.ini
Eve/DarklawWit/char.ini

The pairing option only allows selecting the root folder so in this case both Ema and Eve are paired together and in the wit position. However when either talk they're not shown as paired together it's only showing them separately.
The same happens if they're both using iniswaps as mentioned before.

**Comment by stonedDiscord** [comment]
> to better organise them.

we have iniswaps.ini for that
do not place char.ini files in subfolders of another character

if you want to organize the folders, simply create character folders that start with the base characters name

- Ema
- EmaWitness
- EmaProsecution

as longbyte said, what you tried is unsupported and a hack.
that it works with a single character is bad enough

**Comment by collinxchu** [comment]
Multiple servers I'm aware of use what we nicknamed "megafolders", where they have variants and the like. Usually, though, they use pathing in the char.ini to point to subfolders, not whatever this is.

**Comment by oldmud0** [comment]
Apparently, this is a configuration used by KFO, though it is a moderately cursed one.
