### ISSUE TITLE
Music with special character in the name(s) won't play

### ISSUE THREAD

**Issue by coltongit** [AttorneyOnline/AO2-Client#36]
If you name music like, say, PURSUIT (T&T).mp3 instead of PURSUIT (AA3).mp3, then the client won't even try to play the file, no matter how much you click on the entry. I hope this gets fixed sooner rather than later. I'm also unsure if this is client-side or server-side, but I'll move this bug report if it's not client-side.

**Comment by coltongit** [comment]
It at least happens with serverD, although it may happen with tsuserver too. I'd advise to check both server software to see if the bug exists in each.

**Comment by Parazoid** [comment]
This is not the case in tsuserver, I've tried it, I can't seem to reproduce the bug no matter what special character I use, I even used Japanese unicode characters and it worked fine.

**Comment by oldmud0** [comment]
Not a client issue, then.
