### ISSUE TITLE
Click ADD TO FAV on startup to receive segmentation fault 

### ISSUE THREAD

**Issue by skyedeving** [AttorneyOnline/AO2-Client#373]
1. Launch client
2. Click 'ADD TO FAV'
3. Receive segmentation fault

**Comment by skyedeving** [comment]
https://github.com/AttorneyOnline/AO2-Client/blob/f77ae093e3d5fd86e029cb6309fa3ca34b84fddb/src/lobby.cpp#L284-L287

Without a selection `ui_server_list->currentItem()` returns a `nullptr` and will segfault trying to call a method.
Might be related to #324

**Comment by oldmud0** [comment]
That's one heck of a crash speedrun.
