### ISSUE TITLE
Game reports that APNG plugin loaded: No

### ISSUE THREAD

**Issue by skyedeving** [AttorneyOnline/AO2-Client#375]
![image](https://user-images.githubusercontent.com/76892045/103731875-d535b200-4fab-11eb-9a10-bcffe3ae8a26.png)
1. Launch game
2. Click About
3. Find out near the bottom that `APNG plugin loaded: No` 

Happens on both windows and linux for me. Displaying and animation work on windows. Animation seems broken with linux qt 5.15.2
https://github.com/AttorneyOnline/AO2-Client/blob/9486f44770e6830e9986a254c9b718101d6622da/src/lobby.cpp#L359

# Test
https://github.com/skyedeving/AO2-Client/blob/add-tests/test/test_apng.cpp

**Comment by oldmud0** [comment]
Oops. Try `"apng"` instead of `"APNG"`.

**Comment by skyedeving** [comment]
Can't test on windows but still missing on linux Qt 5.15.2 for me after test has been modified to check both cases.
```c++
  REQUIRE((QImageReader::supportedImageFormats().contains("apng") ||
           QImageReader::supportedImageFormats().contains("APNG")));

```

**Comment by oldmud0** [comment]
Yeah, that's not going to fix QtApng not loading on your local Linux build. You need to link it against a local build of [QtApng](https://github.com/Skycoder42/QtApng/).

**Comment by skyedeving** [comment]
Hmmm, a freshly built QtApng from the repo was linked with but it's still not working. The example provided from the repo works although. I'll look more into this

**Comment by skyedeving** [comment]
Installed QtApng as a package and that seemed to work.

**Comment by oldmud0** [comment]
> Installed QtApng as a package and that seemed to work.

Yeah, I should have asked what distro you were on. It's on the AUR and I think there is also an RPM available.

**Comment by skyedeving** [comment]
No prob, I use a distro called Slackware
