### ISSUE TITLE
Possible QMenu Memory Leaks?

### ISSUE THREAD

**Issue by skyedeving** [AttorneyOnline/AO2-Client#380]
The QMenu objects created are possibly never destroyed. My understanding of Qt isn't high enough to tell if this leaks memory or not.

https://github.com/AttorneyOnline/AO2-Client/blob/d308fc83def2b2d1cb16b88a0a3f9355851f6cb7/src/courtroom.cpp#L3857
https://github.com/AttorneyOnline/AO2-Client/blob/d308fc83def2b2d1cb16b88a0a3f9355851f6cb7/src/courtroom.cpp#L3964
https://github.com/AttorneyOnline/AO2-Client/blob/d308fc83def2b2d1cb16b88a0a3f9355851f6cb7/src/courtroom.cpp#L4053
https://github.com/AttorneyOnline/AO2-Client/blob/d308fc83def2b2d1cb16b88a0a3f9355851f6cb7/src/courtroom.cpp#L4217

https://doc.qt.io/qt-5/qmenu.html#QMenu
https://doc.qt.io/qt-5/qlineedit.html#createStandardContextMenu

**Comment by oldmud0** [comment]
`createStandardContextMenu()` will automatically set the parent, so there's no leak there (memory will be freed when the parent widget is destroyed). The latter two, however, might. If you wanted to be sure not to leak, set the DeleteOnClose attribute:

```cpp
menu->setAttribute(Qt::WA_DeleteOnClose);
```

**Comment by skyedeving** [comment]
Connected the QMenu's `destroyed` signal to a lambda to debug print and found out behaviour:
`connect(menu, &QObject::destroyed, []() { qDebug() << "QMenu Destroyed"; });`

Yeah the first two are confirmed to free on parent widget destruction. The lifecycle seems like it might allow the QMenu's to accumulate like a leak although. The latter two definitely leak. The `setAttribute` suggested works so I'll apply to all four QMenu's in the upcoming PR.
