### ISSUE TITLE
[Master] Inconsistent single-double-click behavior on music list expand/collapse arrows

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#407]
**Describe the bug**
Usually, the expand/collapse arrows by music list categories should only have to be clicked once. However, if music_list_animated is not true, then this behavior can randomly transform into double-clicking, but only on the category you are currently selecting, but sometimes not.

**To reproduce**
1. Join a server
2. Use a theme with at least 15 music list indent
3. Click on the arrow
4. Select the category you're expanding/collapsing
5. Attempt to click on the arrow, this time you'll probably be forced to double-click it for it to work

**Expected behavior**
You should ever only have to click on the expand/collapse arrows once. Additionally, perhaps single-clicking on categories should be enough for expand/collapse behavior as well, but this is up for debate.

**Version:**
 - OS: Windows 10
 - Version or branch: master

**Comment by in1tiate** [comment]
This is known Qt behaviour designed to stop accidental doubleclicks from opening and closing the menu instantly. Closing.

**Comment by in1tiate** [comment]
Reopening, there's something more to this. Present in `2.9.0-rc1`.

**Comment by in1tiate** [comment]
Closing again. This appears to have been resolved by `2.9.0-rc2`.
