### ISSUE TITLE
[Master] Right Click -> Stop Song breaks backwards compatibility

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#410]
**Describe the bug**
You no longer double-click on song categories to stop songs, however, Right Click -> Stop Song only works on supported servers and doesn't work with the outdated method.

**To reproduce**
1. Go to any server not updated for 2.9
2. Right Click -> Stop Song

**Expected behavior**
The song stops. For outdated servers, they just play the category, which will be an invalid song.

**Screenshots**
![image](https://user-images.githubusercontent.com/3470436/104926761-9a6f4900-59b1-11eb-9c32-0901611dbef5.png)

**Version:**
 - OS: Windows 10
 - Version or branch: master

**Additional context**
*Must* be resolved before 2.9 goes live.

**Comment by oldmud0** [comment]
We established that `~stop.mp3` *should* be available by the server as a silence track. Do we want to feature flag this...?

**Comment by in1tiate** [comment]
If we have to feature flag it, we can.

**Comment by oldmud0** [comment]
Oh, there's another hack that I just thought of. Maybe we can just find any category on the list.

**Comment by in1tiate** [comment]
That would break the "has stopped the music" message.

**Comment by in1tiate** [comment]
Finding any category on the list would be a viable compatibility alternative for when we know that the server doesn't support stopping via ~stop.mp3, though
