### ISSUE TITLE
[2.9.0-rc4] Fonts cannot be loaded using their full name

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#422]
**Describe the bug**
When using custom fonts via `courtroom_fonts.ini`, the "full name" of the font is not accepted. This makes using faces other than the default face of a font impossible.

**To reproduce**
1. Attempt to use a custom font's full name in `courtroom_fonts.ini`.
2. See error.

**Expected behavior**
Fonts should be loadable using their full name.

**Screenshots**
Setup:
![image](https://user-images.githubusercontent.com/32779090/105225260-ecd07700-5b23-11eb-9648-c34fa3081e9c.png)
GitLab pipeline build of 2.9.0-rc1:
![image](https://user-images.githubusercontent.com/32779090/105225338-0a054580-5b24-11eb-8980-ffe414dde23e.png)
Dynamic build of 2.9.0-rc1 using Qt 5.14.2:
![image](https://user-images.githubusercontent.com/32779090/105225382-19848e80-5b24-11eb-8118-20a0d4267b14.png)

**Version:**
 - OS: Windows 10
 - Version or branch: 2.9.0-rc1

**Additional context**
Another problem seemingly caused by the pipeline's out-of-date Qt version. Recommend updating to at least 5.14.2.

**Comment by oldmud0** [comment]
Are you using TTFs or OTFs?

**Comment by in1tiate** [comment]
TTFs. OTFs are still broken per #224.

**Comment by oldmud0** [comment]
Is the TTF installed on the OS?

**Comment by in1tiate** [comment]
Yes. As far as I know, installing the font is the only way to use it in AO2, as there's no code for loading it from a file.

**Comment by oldmud0** [comment]
Okay, just wanted to make sure nothing was snuck in, though I see it's not relevant to the issue.

**Comment by Crystalwarrior** [comment]
Is this resolved?

**Comment by in1tiate** [comment]
Resolved by the update to the CI. Closing.

**Comment by in1tiate** [comment]
Present in `rc4`.

**Comment by oldmud0** [comment]
I tried `Suburga 2 Semi Condensed` and it worked.

**Comment by oldmud0** [comment]
If you use the font name listed in the font viewer as opposed to the TTF's file name, it should work. Closing.
