### ISSUE TITLE
[2.9.0-rc1] Blankposts are no longer shown in the IC log unless they are the first message in the log

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#423]
**To reproduce**
1. Send a message.
2. Blankpost.
3. See error.

**Expected behavior**
Blankposts should be visible in the IC log.

**Version:**
 - Version or branch: 2.9.0-rc1

**Comment by skyedeving** [comment]
It might be due to here:
https://github.com/AttorneyOnline/AO2-Client/blob/c13e6b7ab0fd36ebf784294b2788ae365109a24f/src/courtroom.cpp#L2135-L2148

No blankposts in the IC log seems to be intended behaviour now? Due to the condition in the if statement

**Comment by in1tiate** [comment]
@Crystalwarrior
