### ISSUE TITLE
[2.9.0-rc1] In some cases, buttons can use both text mode and image mode

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#425]
**Screenshots**
![image](https://user-images.githubusercontent.com/32779090/105568056-370c5080-5cfc-11eb-8467-3dd6e1ce0c4f.png)

**Version:**
 - Version or branch: 2.9.0-rc1

**Additional context**
basically this should never happen

**Comment by Crystalwarrior** [comment]
Steps to reproduce?
