### ISSUE TITLE
New client versions "break" old themes.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#427]
In short, because of the default behavior of themes when something isn't specified (put it in its default location), older themes which did not incorporate these assets will simply have them strewn across the theme in seemingly arbitrary ways.

I suggest having some kind of flag that's off by default which checks if the theme wants to inherit features from the default theme.

To reproduce: Use literally any theme circa a year or two ago.

**Comment by in1tiate** [comment]
I've made a working implementation of this on my local machine, but honestly I don't think this is a good idea. Too much of AO relies on default theme inheritance, including the vanilla base themes.

**Comment by Crystalwarrior** [comment]
> I've made a working implementation of this on my local machine, but honestly I don't think this is a good idea. Too much of AO relies on default theme inheritance, including the vanilla base themes.

Closing in that case

**Comment by Crystalwarrior** [comment]
Ended up making a solution for this anyway! You can now define `default_theme` in courtroom_design.ini, so if you do for ex. `default_theme=` or `default_theme=-` or w/e, you'll be able to make that particular theme parented to Nothing, making it independent.
https://github.com/AttorneyOnline/AO2-Client/pull/466
