### ISSUE TITLE
Escaped Characters cutting Character Names in Character Select

### ISSUE THREAD

**Issue by caleb-mabry** [AttorneyOnline/AO2-Client#430]
**Describe the bug**
[I was working on an issue related to TSU](https://github.com/AttorneyOnline/tsuserver3/issues/124) and noticed that even sending the client a list of characters with escape characters properly handled, it is being presented improperly. 
I am under the assumption that the `SC` packet is what the client uses to display information

**To reproduce**
1. Download TSU's Master Branch
2. In the characters.yaml file, put an & in any of the characters names
3. In TSU edit 'aoprotocol.py' `net_cmd_rc` method to be
```py
    def net_cmd_rc(self, _):
        """Asks for the whole character list (AO2)

        AC#%

        """
        escaped_character_list = self.server.char_list
        for index, character in enumerate(escaped_character_list):
            character: str
            if '&' in character:
                escaped_character_name = character.replace('&', '<and>')
                escaped_character_list[index] = escaped_character_name
        print(escaped_character_list)
        self.client.send_command('SC', *escaped_character_list)
```
4. Connect to local TSU and see that the name is still cutoff

**Expected behavior**
The character information should still appear even if there's an escape code in the name.

**Screenshots**
![image](https://user-images.githubusercontent.com/36182383/105615104-00861280-5d9c-11eb-810b-fb02ad88f2e5.png)
![image](https://user-images.githubusercontent.com/36182383/105615108-0d0a6b00-5d9c-11eb-941e-d01c84c27bcc.png)

**Version:**
 - OS: Windows 10
 - Version: 2.8.5

**Additional context**
Here's an output of the list that I send to the client with the escaped character 
`['Adrian', 'Apollo', 'April', 'Armstrong', 'Atmey', 'Butz', 'Diego', 'Edge<and>worth', 'Edgeworthw', 'Ema', 'EmaSkye', 'Franny', 'Franziska', 'Gant', 'Gavin', 'Gavin K', 'Godot', 'Gregory', 'Grossberg', 'Gumshoe', 'Gumshoey', 'Hawk', 'Hobo_Phoenix', 'Ini', 'Judge', "Judge's Bro", 'Klav', 'Klavier', 'Kristoph', 'Lana', 'Layton', 'Lotta', 'Luis', 'Maggey', 'Manfred', 'Marshall', 'Matt', 'Maya', 'Mia', 'Miles', 'Oldbag', 'Payne', 'Pearl', 'Phoenix', 'Valant', 'Vasquez', 'Wellington', 'Winston', 'WinstonPayne', 'Young Mia', 'Zak']`

**Comment by oldmud0** [comment]
The packet is likely being scrubbed too early in the client after being received.

**Comment by skyedeving** [comment]
The behaviour comes from these two lines in the same function:
https://github.com/AttorneyOnline/AO2-Client/blob/c13e6b7ab0fd36ebf784294b2788ae365109a24f/src/packet_distribution.cpp#L11
https://github.com/AttorneyOnline/AO2-Client/blob/c13e6b7ab0fd36ebf784294b2788ae365109a24f/src/packet_distribution.cpp#L334

At the start the received packets are decoded by converting escaped chars to the actual ones. The issue is that ampersand characters are also used as the split token for the received character list. Fix will have to be making an exception for the packet.
