### ISSUE TITLE
Judge Buttons don't interrupt each other and stop appearing when spammed

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#460]
**Describe the bug**
Judge Buttons don't interrupt each other and stop appearing when spammed

**To reproduce**
1. go to server
2. spam witness testimony/ce/guilty/not guilty
3. uh oh they don't appear

**Expected behavior**
The judge button interrupts itself

**Screenshots**
https://user-images.githubusercontent.com/3470436/107616245-bc7d8380-6c5e-11eb-8c50-7fcc7f168af9.mp4

**Version:**
 - OS: Windows 10
 - Version or branch: master

**Additional context**
sound still plays

**Comment by in1tiate** [comment]
confirmed to be caused by continuous playback being applied incorrectly
