### ISSUE TITLE
[2.9.0-rc3] Widescreen backgrounds/characters are not properly cropped into 4:3 res themes

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#471]
**Describe the bug**
Incorrect cropping of widescreen BGs for 4:3 themes, but only when the bg is displayed after a theme reload

**To reproduce**
1. Join area with widescreen bg and reload theme
2. Be on a 4:3 theme

**Expected behavior**
Cropped as it does if you switch to a dif pos w/o reload theme (see video)

**Screenshots**
![](https://cdn.discordapp.com/attachments/353369729328611330/810817175257874452/unknown.png)
![video](https://cdn.discordapp.com/attachments/353369729328611330/810818652734619678/s0V9TBxTHQ.mp4)

**Version:**
 - OS: Windows 10
 - Version or branch: 2.9.0-rc3

**Additional context**

**Comment by in1tiate** [comment]
Cannot reproduce on current `master`.
