### ISSUE TITLE
[2.9.0-rc3] Server pos is ignored in favor of client's pos dropdown

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#472]
**Describe the bug**
When you attempt to utilize a custom pos outside of the pos dropdown, you will be forced into the character's default pos.

**To reproduce**
1. Go to an area with a BG outside of the normal dropdown pos
2. Switch to a pos using /pos <name>
3. Speak
4. You'll be forced back into the character's default pos

**Expected behavior**
Server's pos is prioritized and not overwritten needlessly.

**Screenshots**
$H: Position set to debate. 
$H: Position changed. 
$H: Position set to wit. 
$H: Position set to pro. 
$H: Position set to debate. 
$H: Position changed. 
$H: Position set to pro. 
$H: Position set to debate. 
$H: Position changed. 
$H: Position set to wit. 
![video](https://cdn.discordapp.com/attachments/353369729328611330/810823365648580618/RtkaPGhCeo.mp4)

**Version:**
 - OS: Windows 10
 - Version or branch: 2.9.0-rc3

**Comment by in1tiate** [comment]
Not a bug. Custom positions _must_ be defined in design.ini for them to be used.

**Comment by Crystalwarrior** [comment]
> Not a bug. Custom positions _must_ be defined in design.ini for them to be used.
> 
> If this behavior is undesirable, maybe server positions should be temporarily added to the dropdown?

Yes, that's Good solution

**Comment by oldmud0** [comment]
Your video doesn't work anymore, by the way.
