### ISSUE TITLE
Newline characters are not scrubbed from IC log

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#51]
The in-character chatbox scrubs newline characters from input text, but not the IC log. We can fix this in three ways:

- Allow newline characters to be printed in the chatbox.
- Scrub newline characters from the IC log.
- Claim this is "intended behavior" and scrub newline characters on the server side instead.

**Comment by Crystalwarrior** [comment]
I remember running into this in 2.8. First I printed '\n' where newlines were, but this ended up making text unreadable. Currently in 2.8, the newlines are preserved, but this ofc can cause issues especially with spam. Perhaps it should be scrubbed?

**Comment by oldmud0** [comment]
Eh. Let's just say it's "intended behavior."
