### ISSUE TITLE
Global scaling override defined in settings

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#515]
Per Crystal#5638 on Discord:
> If it doesn't exist already, would it be possible to have a setting that would be a universal "override" to the scaling = x line on the .ini?
> So instead of the client looking at the char.ini for what to do (and going by-pixel for everything when it doesn't exist), the setting would just tell the client to either treat everything as pixels, as smooth, or by "default" (what is done currently)

My own thoughts on the matter are as follows: This is certainly possible to implement, and to expand further it would be useful to be able to toggle whether or not this global setting would override *everything* or just override the default setting (which is Fast)

**Comment by oldmud0** [comment]
Per discussion, it would be more useful to have the option configure the default than it would be to override everything.
