### ISSUE TITLE
Support HTTP-based server list

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#550]
The current master server is relatively expensive and difficult to maintain. The MS protocol depends on raw TCP to perform simple transactional operations that could otherwise have been done over HTTP. Side effects have included:

- Multiplexing over WebSockets to support webAO
- Probing every server every 2 minutes just to get player counts to sort the server list
- Zombie servers that have been down for months
- Inexplicable issues connecting by newcomers

Introducing an HTTP-based server list. You can demo it at [`https://ms3.oldmud0.workers.dev`](https://ms3.oldmud0.workers.dev). The API is so braindead, even a lobotomite could use it.

Migration plan:

- Replace client and webAO MS connection with HTTP API
- Proxy any legacy MS calls until sunset date
- Replace server MS connection with HTTP API

# API reference

## `GET /servers`

Get a list of servers.

### Response

```ts
{
  ip: string,
  port: number,
  ws_port?: number,
  players: number,
  name: string,
  description?: string
}[]
```

## `POST /servers`

Add, modify, or renew a server on the list. Once a server has been posted (advertised), it has a lifetime of five minutes before the entry must be renewed with another POST call.

### Request

```ts
{
  port: number,
  ws_port?: number,
  players: number,
  name: string,
  description?: string
}
```

#### Success

200 OK with empty body.

#### Failure

```ts
{
  title: string,
  errors: string[]
}
```

## `GET /motd`

Get the message of the day.

### Response

An HTML-formatted document containing the message of the day.

**Comment by dmcnvbgfgh-cancer** [comment]
This complicates implementation, but also opens up heaps of new possibilities and more flexibility, for instance, the client reporting its version & features to the MS, then the MS sending only servers that are compatible. Maybe as a checkbox?
Also, I feel like the POST can easily be done with headers, which simplifies it and removes the need for json parsing (*shudder*)

**Comment by oldmud0** [comment]
JSON APIs are standard across the board. We can use headers for some metadata - good idea - but the API will use JSON.

**Comment by oldmud0** [comment]
Completed
