### ISSUE TITLE
Autosave private evidence

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#553]
**Is your feature request related to a problem? Please describe.**
It sucks to create an inventory of private evidence, only to crash or disconnect for any reason, and when you open the client back up all of that evidence is gone.

**Describe the solution you'd like**
Every time the client has to close for any reason, or perhaps during a certain interval, all of your private evidence will be saved into base/evidence/autosave.ini, and when you launch the client that private evidence autosave will be loaded automatically.

**Comment by Crystalwarrior** [comment]
Private evidence could auto save any time it's modified maybe

**Comment by Salanto** [comment]
Resolved in PR #778
