### ISSUE TITLE
"Search" not preserved when A/M is toggled.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#555]
Upon clicking the A/M button, the "search" box is, of course, emptied out so that the other category can be seen in its entirety. When toggling back, however, one must re-type whatever it was they had been searching at the time. While not strictly a bug, it is annoying from a UX perspective.

**Comment by in1tiate** [comment]
wasnt doing anything important anyway, give me half an hour

**Comment by in1tiate** [comment]
12 minutes, new record
