### ISSUE TITLE
Non-streamable audio links played as music freeze the client on Linux only

### ISSUE THREAD

**Issue by Dedinsaid228** [AttorneyOnline/AO2-Client#565]
Hello. I ran AO 2.9.1 on Ubuntu 20.04 and Fedora 34 which were running on Vmware Workstation 16. For some reason, including music via Discord link causes AO to freeze.

Just in case, I recorded a video:
https://drive.google.com/file/d/16lO1lN6uHKNSB7lRJgAbGJP8g4A3su7Q/view

Link used in the video:
https://cdn.discordapp.com/attachments/632918518265937920/849351585964490762/brandon2_.mp3

P.S. Sorry for my bad english.

**Comment by in1tiate** [comment]
The link you used won't work for streaming music, as it needs to be streamable for AO to use it. However, this should not cause the client to freeze. I'll test this on Windows to see if this is a platform-specific bug.

**Comment by in1tiate** [comment]
@Dedinsaid228 Can you try this link to see if it freezes you too?
https://vgmsite.com/soundtracks/gyakuten-saiban-sound-box/qijggzruko/3-03%20Gyakuten%20Saiban%203%20-%20Trial.mp3

**Comment by Dedinsaid228** [comment]
@in1tiate AO does not freeze with this link.

**Comment by in1tiate** [comment]
Alright, so the problem is with non-streamable links on Linux only. Sounds like a possible BASS issue.

**Comment by oldmud0** [comment]
Tried on one of BASS's sample programs (netradio) - same thing. Might post something in the support forums.

**Comment by oldmud0** [comment]
Can't reproduce anymore with netradio on BASS 2.4.16 on Linux (lots of changes were made).

In addition, it is now possible to restart BASS while preserving all channels (BASS_DEVICE_REINIT).
