### ISSUE TITLE
Non-WAV blips are not being played

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#57]
`.wav` is being assumed instead of calling `get_sfx_suffix` to get the sound effect's likely extension:

https://github.com/AttorneyOnline/AO2-Client/blob/33dd06e9aa4de11c4e8f9e51bebfdede39c61573/src/courtroom.cpp#L2015

(Sorry, I'm on the development branch and can't be bothered to switch back to the master branch just for a one-line change since it messes up my project files every time I switch between the two branches.)

**Comment by perplexedMurfy** [comment]
Understandable, have a good development
