### ISSUE TITLE
Music label incorrectly adds [Missing] tag while streaming with slow internet

### ISSUE THREAD

**Issue by Salanto** [AttorneyOnline/AO2-Client#570]
**Describe the bug**
Streaming music over a slow internet connection causes the client to show remote content as missing, even if it's present and playable. Introduced by #549 

**Version:**
 - OS: Windows 10
 - Version or branch: master

**Comment by oldmud0** [comment]
There is a new version of BASS that is out now (BASS 2.4.16.3). Please try it.

**Comment by in1tiate** [comment]
@Salanto Is this still an issue with the new BASS version?

**Comment by oldmud0** [comment]
Should be fixed in #609
