### ISSUE TITLE
Automatic generation of shaded buttons is nonfunctional

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#572]
**Describe the bug**
Automatic generation of shaded buttons no longer functions

**Version:**
 - OS: Windows 10
 - Version or branch: master (https://github.com/AttorneyOnline/AO2-Client/commit/a4b5023088b4b00d2a54cd36909a95336851c898)

**Comment by oldmud0** [comment]
Definitely related to the vpath system. I thought I had fixed it, but I guess not.

**Comment by oldmud0** [comment]
Fixed in #622
