### ISSUE TITLE
"Realization" effect uses the "realization.png" button from the theme instead of the correct effect folder "realization.png"

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#574]
**Version:**
 - OS: Win10
 - Version or branch: master

**Comment by in1tiate** [comment]
Suggestion: as breaking theme changes have been introduced before, it would make sense now to rename the realization button's graphic to "realization_button.png" as well as any other buttons that may collide with existing assets.

**Comment by in1tiate** [comment]
Confirmed still present as of 12/4/2021

**Comment by oldmud0** [comment]
Fixed in #629
