### ISSUE TITLE
Under certain circumstances, pairing may function incorrectly

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#577]
![image](https://user-images.githubusercontent.com/32779090/127777246-23deb158-dcc8-4756-9df4-affc98912392.png)

**Comment by RealTheDatrix** [comment]
In case it's needed I got some footage for the described problem:

https://www.youtube.com/watch?v=_jwhs7MVHOk

**Comment by collinxchu** [comment]
Exact shit happens to me, too. Pair up, have one post, then the other post, then have the "other" post a second time. Bababooey the original vanishes.
