### ISSUE TITLE
guard button appears without inputting the correct mod password

### ISSUE THREAD

**Issue by Parazoid** [AttorneyOnline/AO2-Client#59]
When you use the **"/login"** command, no matter what input you give the Guard button appears. This is caused by the client checking if the message starts with **"/login"**, instead of checking if the password is correct or not.

**Comment by oldmud0** [comment]
Clearly, it's a feature.

The best way to fix this would be to remove the guard button and create a new option in the Settings dialog called "Ignore mod calls".

**Comment by oldmud0** [comment]
Closed: https://gitlab.com/AttorneyOnline/AO2-Client/issues/59
