### ISSUE TITLE
Custom Shout Crash & Odd Behaviour

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/AO2-Client#592]
**Describe the bug**
Custom shout displays on characters that lack it showing the custom button, and crashes with characters that do have a custom shout.

**To reproduce**
Steps to reproduce the behaviour for custom shout button shout:
1. Select a character who does not have a custom shout
2. See custom shout button visible
3. Try to use custom shout
4. See custom shout button on screen

Steps to reproduce the behaviour for game crash:
1. Select a character who does have a custom shout
2. See custom shout button visible (as it should be)
3. Try to use custom shout
4. Game stops responding

**Expected behaviour**
Expected is custom shouts to not crash the game, and for the button to not display for those who do not have a custom shout (unless that got changed), nor for them to be able to display the custom shout button as a shout in the viewport.

**Screenshots**
![bruhthur moment](https://user-images.githubusercontent.com/30537683/132998052-b9d0674a-b0c1-4e59-87cc-c56f4256ddc6.png)
![blackquill when the](https://user-images.githubusercontent.com/30537683/132998060-3b33f149-7072-4c55-8abb-8e8b0bcbdc44.png)

**Version:**
 - OS: Windows 10
 - Version or branch: current master

**Additional context**
ignore the theme

**Comment by in1tiate** [comment]
Likely introduced by VPaths. @oldmud0, any ideas?

**Comment by oldmud0** [comment]
I would need a clear reproduction to understand the cause.
