### ISSUE TITLE
Additive Text repeats other players text. 

### ISSUE THREAD

**Issue by KenTheTester** [AttorneyOnline/AO2-Client#593]
**Describe the bug**
Additive Text adds text of other players.

**To reproduce**
Step 1 - Join A Server.
Step 2 - Have Additive Text enabled.
Step 3-  have someone who is not you say anything. 
Step 4- have a blankpost happen.
Step 5- say something after blank post.
Step 6 - You now have what you said, plus what the person prior to blankpost said. 

**Expected behavior**
I presume additive text from its description is supposed to add on text to your last message, not add on other peoples messages, as if your saying it. 

**Screenshots**
Included Below. 

**Version:**
 - OS: (Windows 10)
 - Version or branch: (Master)

Some Context
"Messing around on AO, found this issue on HDF Client [we just use a slightly more recent one than 2.9.1] . Then tested with master client, issue is the same. Tested on more than one Server."

<img width="1226" alt="Screenshot 2021-09-13 165029" src="https://user-images.githubusercontent.com/73434721/133154842-2df29539-4603-4b30-968d-f6f19d3c19d0.png">

![Screenshot 2021-09-13 165044](https://user-images.githubusercontent.com/73434721/133154847-840a95de-e0a1-4997-8186-b162c3e2c026.png)

![Screenshot 2021-09-13 165059](https://user-images.githubusercontent.com/73434721/133154850-104a8540-b1cf-45b4-ab84-34b42c26388f.png)

![Screenshot 2021-09-13 165125](https://user-images.githubusercontent.com/73434721/133154855-0d957b1f-4fae-4a46-b193-d03f64ac7f09.png)

**Comment by oldmud0** [comment]
I vaguely recall this issue having appeared before. Can you submit a demo please?

**Comment by Crystalwarrior** [comment]
This might be a server issue because additive validity is checked by the server

**Comment by Crystalwarrior** [comment]
Server-sided problem.
"Additive" will work on top of other chat regardless of who said what unless the server goes out of their way to prevent this. Reason why it's designed this way is if the server wants to allow the CM's to add text on top of previously spoken message.
