### ISSUE TITLE
Sticky Sounds is broken with FrameSFX and with short/no-preanimations.

### ISSUE THREAD

**Issue by LiterallyWho2** [AttorneyOnline/AO2-Client#594]
You can spam long SFXs and they'll stack over each other because the Sticky Sounds button does not do absolutely anything. Best seen with using FrameSFX where you can get long sfxs to play every single frame on loop.
Wasn't like this in 2.8.

**Comment by in1tiate** [comment]
I assume you deleted the template for bug reports, but we have that for a reason. Please provide the exact steps to take in order to reproduce this issue alongside the version of the client where the issue can be experienced.

**Comment by LiterallyWho2** [comment]
Apologies. This happened on 2.9.1
1. Open up a char ini
2. make a framesfx of something, for example, a talk animation
3. apply a sound to every single frame, ideal with a long one to be extra annoying
4. Talk with the emote in client.

What should be expected is that the next sound effect stops the previous, unless sticky sounds was checked. But it doesn't.

Here should be a video demonstration. Sound warning.
https://user-images.githubusercontent.com/90486307/133172806-b81140a3-7ac7-4dbe-ba24-26ee4782ad1f.mp4

**Comment by in1tiate** [comment]
I think you're mistaken about the way Sticky Sounds works - it has nothing to do with sounds cutting each other off.

As of 2.9, sound effects are played using multiple channels. This is a feature - previously it was impossible to layer sound effects, leading to the advent of combined sfx where they have been layered in an audio editor. 

As for the issue of people being irritating with long sound effects - this is not a new problem. I advise punitive measures against those users or, failing that, simply using a shout will cause all FrameSFX to cut short.

**Comment by LawfulDickish** [comment]
An addendum regarding this issue worth considering: When sound effects are spammed in this matter, they cannot be muted; they are unaffected by any client volume slider and will play at their starting volume until they are finished.

**Comment by oldmud0** [comment]
I have changed the title of the issue to represent the complaint. Adding an override for channel count could be a potential enhancement, but not a likely one.
