### ISSUE TITLE
hld/hlp keeping the bench from the last displayed pos.

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/AO2-Client#597]
**Describe the bug**
hld/hlp (positions with no benches) would keep the last bench displayed on screen if someone were to talk there.

**To reproduce**
1. Be in a background with benches/stands (a courtroom for example).
2. Talk in a position with a bench or stand.
3. Talk in a position that does not have one (such as hld/hlp in courtroom backgrounds).
4. You will retain the bench and have it cover your sprite.

**Expected behavior**
The positions without benches should have no bench be displayed.

**Screenshots**
![witness stand](https://user-images.githubusercontent.com/30537683/133532150-2151fdd8-bd6f-443a-b1ac-77af70cbb546.png)
![bench](https://user-images.githubusercontent.com/30537683/133532152-622dcaf0-f795-4341-8919-4965fd115c3e.png)
![judge bench](https://user-images.githubusercontent.com/30537683/133532158-b4b56eb5-a173-4c07-8c60-5db0260c773d.png)

**Version:**
 - OS: Windows 10
 - Version or branch: master

**Additional context**
There was also a game crash involving change to hld via the dropdown, but I couldn't replicate it since. That said, if it isn't just a fluke (which it probably was) it's probably related somehow.

**Comment by in1tiate** [comment]
fixed by #598
