### ISSUE TITLE
Callword doesn't work if PRE-Anim is interrupted.

### ISSUE THREAD

**Issue by komahinaa** [AttorneyOnline/AO2-Client#60]
Callword feature doesn't work if a pre-anim is too long/interrupted.
If it's too long, it waits for pre-anim to end, making it delay.
If it's interrupted, it won't start.

**Comment by Crystalwarrior** [comment]
uhhh wait do callwords work in 2.8 currently

**Comment by komahinaa** [comment]
> uhhh wait do callwords work in 2.8 currently

this was. literally from 2019

**Comment by Crystalwarrior** [comment]
Will close until there's a documented occurrence of this happening in 2.8
