### ISSUE TITLE
char.ini Targets the Folder over the .gif

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/AO2-Client#602]
**Describe the bug**
If the ini tries to find a gif file that has the same name as a folder in the same directory, it'll target the folder rather than the gif, and fail to load the gif.

**To reproduce**
I'm using Bonny de Famme's character folder and ini as an example here.

Her 9th emote is

9=Parasol#Pre/parasol#/Parasol/parasol#1#

and the Pre folder looks like this

![image](https://user-images.githubusercontent.com/30537683/135942270-04728fe9-c312-41f0-b8c7-c15d81011679.png)

Due to there being both the Parasol folder and parasol.gif, the issue happens

1. Use an emote where there's also an identically named folder in the same directory as the gif you're targetting (like Bonny's 9th emote).
2. The pre/emote doesn't play (in the example, just the pre).

If you rename the folder, it works fine, and if you rename the emote and change the relevant field in the ini, it also works fine.

**Expected behavior**
In 2.9.1, it targets the .gif and plays the pre properly.

**Version:**
 - OS: Windows 10
 - Version or branch: master

**Additional context**
I doubt there are many cases where this is an issue, since it was so hard to find and spot that it was because there was an identically named folder, but it still seems odd to target the folder over the gif.

**Comment by oldmud0** [comment]
Can't reproduce in master.
