### ISSUE TITLE
Emote Previews

### ISSUE THREAD

**Issue by TailaBlu** [AttorneyOnline/AO2-Client#606]
My suggestion is that Attorney Online 2.9 implements an emote preview system similar to Danganronpa Online, so that players can figure out what they’re about to do before they do it. Buttons can only hold so much information about an animation or image, especially when most themes have a viewport larger than 40x40 pixel squares.

I’ve heard a few issues regarding this idea that I want to address with further suggestions: Make this a toggleable preview in settings so that the people who don’t want an emote preview can go without, or - better yet - they can trigger the emote preview in multiple different ways. Perhaps a set hotkey or they can make one of the options as simple as holding the mouse on the button they want to preview the emote of.

The issue of the size of the preview is also important, there are two ways to go about this. It can be theme dependent, reflecting the viewport size and/or the image paired with the preview that goes with the theme itself, or it can be set on a client basis, meaning that it is not tied to a specific theme and is instead reliant on what the client’s settings are. There could also be a mix of both, where the preview size is set to specific predetermined settings and no larger or smaller.

What do you think of this?

**Comment by Crystalwarrior** [comment]
I like the idea of making it a client setting on preview tool tip size, how long you mouse over the button until the tool tip appears, and maybe an alternative way to trigger it through right click

**Comment by oldmud0** [comment]
I'm not sure about how to go about implementing this as QToolTip does not support setting the pixmap like a QLabel does. Any ideas would be appreciated.

**Comment by Crystalwarrior** [comment]
> I'm not sure about how to go about implementing this as QToolTip does not support setting the pixmap like a QLabel does. Any ideas would be appreciated.

Instance a qlabel instead of a qtooltip when moused over long enough? Basically replacing it entirely and making it behave similar
Alternatively, you could have the preview open in an entirely new window but that means tooltip method is not gonna happen, rather right-click context menu one

**Comment by Crystalwarrior** [comment]
Okay we just came up with a cool idea that will take us like 0 work:
Right-click -> Open (Pre/Idle/Talk/Post) Emote
So it would open pre/(a)/(b)/(c) emotes, if present.
If not present it won't show the right-click option.
And, it will open the file in the default program on your OS, such as an image viewer, or web browser.

**Comment by Crystalwarrior** [comment]
Apparently this is how DRO implements this: https://github.com/Chrezm/DRO-Client/pull/198/commits/ab0400c4808f3042bb23ff805054e3dba1d01bdd
we can use it as reference

**Comment by oldmud0** [comment]
Seems simple enough....

**Comment by Crystalwarrior** [comment]
I have an idea.
What if this same preview window reflects the current background, pair offsets, etc.?
And maybe it should be its own window you can drag around rather than a tool tip, and you can bring it up via context menu?

**Comment by oldmud0** [comment]
No because that would require a refactor of the viewport to its own class. Unless you want to do that :^)

**Comment by Crystalwarrior** [comment]
Uhhh no lol @oldmud0

**Comment by oldmud0** [comment]
I would say let's use the current background for the backdrop on the preview.

**Comment by Salanto** [comment]
Resolved in PR #774
