### ISSUE TITLE
SFX_Remove Button does not appear

### ISSUE THREAD

**Issue by Crystal2002** [AttorneyOnline/AO2-Client#610]
**Describe the bug**
When selecting an SFX from the `sfx_dropdown`, the corresponding `sfx_remove` button does not appear.

**Screenshots**
Left is AO 2.9.1 (Final Release), Right is AO 2.8.5. Both are using the default theme included in AO 2.8.5.
![](https://puu.sh/IsZkn/018f071920.png)

**Version:**
 - OS: Windows 10
 - Version or branch: 2.9.1 (Final Release)

**Comment by oldmud0** [comment]
Can't reproduce.
