### ISSUE TITLE
Drop compatibility for Qt < 5.15

### ISSUE THREAD

**Issue by likeawindrammer** [AttorneyOnline/AO2-Client#618]
Currently Ubuntu 18.04 and Qt 5.9 is targeted.
To simplify development I suggest to target Ubuntu 22.04 once it's released and with it Qt 5.15.
Also remove code paths for previous versions of Qt, as well as rewrite code that may work but uses apis that were marked as deprecated with 5.15.

- [x] Target Ubuntu 22.04
- [x] Remove code paths for Qt < 5.15
- [x] Rewrite code using deprecated apis

**Comment by Salanto** [comment]
Sufficent steps have been taken to adress the mentioned points.
