### ISSUE TITLE
Looping SFX of paired partners don't stop when a non-pair talks.

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#63]
This causes unpleasant overlapping SFX even after the original character disappearing off screen.
(@Parazoid, https://gitlab.com/AttorneyOnline/AO2-Client/issues/63)

**Comment by Crystalwarrior** [comment]
Does this still occur in 2.8?

**Comment by Crystalwarrior** [comment]
oops

**Comment by scatterflower** [comment]
seems to be the same issue as #66
