### ISSUE TITLE
Sound list doesn't play sound when selected unless preanim is on

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#633]
**Describe the bug**
When I was making 2.9 i went out of my way to make the sound list play sound when it was selected regardless of preanim check box. However, at some point, for some bizarre reason, it's back to the old clunky and limited way.

Reason why sound list is independent is because you might want to play a sound effect during an idle state of a preanim emote, which is needlessly difficult otherwise. 

**To reproduce**
1. Select sound from sound list
2. Send message
3. Sound doesn't play but it's still cleared
4. Enable preanim, select sound again
5. This time it plays but the preanim plays too

**Expected behavior**
The sound plays regardless of preanim

**Screenshots**

**Version:**
 - OS: ( Windows 10)
 - Version or branch: 2.9.1-1
 
**Additional context**

**Comment by Crystalwarrior** [comment]
this is a pretty big and annoying regression lol

**Comment by in1tiate** [comment]
I reverted this behavior because it was done exceptionally poorly and broke existing functionality - I actually thought it was unintended due to this. Apologies for being annoying. 

I'll get to this when I get the time.

**Comment by Crystalwarrior** [comment]
@in1tiate Can you tell me which commit you reverted this in?
