### ISSUE TITLE
BG misplaced/resized incorrectly when theme changes

### ISSUE THREAD

**Issue by Crystal2002** [AttorneyOnline/AO2-Client#635]
**Describe the bug**
Background image does not re-adjust to the viewport correctly until background image changes (be it from a new folder or new position).

**To reproduce**
1). Select any large-resolution theme (i.e. Ace Attorney 2x)
2). Change from Settings menu to any theme where the viewport is sized differently and/or placed differently
3). Refresh theme. Rinse and repeat.

**Expected behavior**
Viewport should be accomodating the background correctly upon refreshing/changing of the theme.

**Screenshots**
Example after changing from AA 2x -> AOHD (by Jouto) -> FullChar -> KFO qHD
![](https://puu.sh/IInTt/0f174debf5.png)

**Version:**
 - OS: Windows 10
 - Version or branch: 2.10 Alpha ([Actions Build #417](https://github.com/AttorneyOnline/AO2-Client/actions/runs/1814131487) & [Actions Build #411](https://github.com/AttorneyOnline/AO2-Client/actions/runs/1672929659)) 

Note: Problem is not present in 2.9.1 Official Release

**Comment by Crystalwarrior** [comment]
![Attorney_Online_Yo4XZoOwfB](https://user-images.githubusercontent.com/3470436/154693147-fc217787-78d5-48dd-8e46-d13a78b2dac6.gif)
