### ISSUE TITLE
Show emote buttons in emote dropdown, char icons in iniswaps

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#638]
**Is your feature request related to a problem? Please describe.**
Similar to how colors have an image left to the dropdown text, being able to see what you're selecting from the dropdown directly would be very good.

**Describe the solution you'd like**
Something like this:
![image](https://user-images.githubusercontent.com/3470436/153648872-035a55f9-f565-405c-b624-bc38f009f3f6.png)

For all dropdowns of elements that could have a preview image (emotes, iniswaps)

**Comment by oldmud0** [comment]
That actually looks pretty darn good. We should do this. I upvote
