### ISSUE TITLE
Effect Offsets w/ Character

### ISSUE THREAD

**Issue by Crystal2002** [AttorneyOnline/AO2-Client#639]
(Most of this is Copy/Pasted from my previous request, since it's pretty much same everything)

**Is your feature request related to a problem? Please describe.**
Not really a problem, but it would be nice to have a way to tell the client that certain effects should be affected by the X/Y offsets being checked and others shouldn't be. Some people do use the Effects system as a "Character Overlay" system to help cut down on custom content file size, so having this would exponentially assist them in keeping the sizes down.

**Describe the solution you'd like**
We currently have effects.ini that keeps track of if the effect should be stretched and if it should be rendered over or under the chatbox. Perhaps another variable could be added to this for if the effect should move with offsets, with the default setting as that effects will not offset.

**Additional context**
What currently happens when a character w/ an effect is slid (the effect layer is the visor):
![](https://cdn.discordapp.com/attachments/646487005303144458/941810894877384764/unknown.png)

Mockup of intended behavior:
![](https://puu.sh/IIx2L/cd44c227aa.png)

Sample Files:
[Black Heart w/ Effects](https://drive.google.com/file/d/1cX8cZcFU39dmjM9fX5fz9sdiOFXolszY/view)

**Comment by in1tiate** [comment]
Possible alternative way of achieving this was developed in #490. @Crystalwarrior, thoughts?
