### ISSUE TITLE
How do we feel about changing the "No Interrupt" checkbox name?

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#64]
As it currently stands, the name "No Interrupt" is a bit misleading and counter-intuitive, you would expect that it disables the emote you're using from being interrupted but instead it only increases the chance of it getting interrupted as it forces the text to display over the pre-animation. Usually you can't interrupt pre-animations without using an interjection bubble.
What would we change it to if we did change it?

(@Parazoid, https://gitlab.com/AttorneyOnline/AO2-Client/issues/62)

**Comment by vintprox** [comment]
- Talk at go
- Rush say
- Say now

**Comment by Crystalwarrior** [comment]
* Instant Text
* Instant Message
* Concurrent
* Immediate
* Talk Pre
* Pretalk
* Communicate at the same time as the preanimation is being played

**Comment by vintprox** [comment]
> * Immediate

This!

**Comment by oldmud0** [comment]
Very well. Could you convert into a pull request please?

**Comment by Crystalwarrior** [comment]
:|
