### ISSUE TITLE
Showname Text is Masked to Chatbox

### ISSUE THREAD

**Issue by Crystal2002** [AttorneyOnline/AO2-Client#640]
**Describe the bug**
Name and screenshots say all.

**Screenshots**
The "t" in "Heart" should not be clipping like that
![](https://cdn.discordapp.com/attachments/646487005303144458/941819327051599902/unknown.png)

What should be happening
![](https://cdn.discordapp.com/attachments/353369729328611330/839153870100889650/unknown.png)

**Version:**
 - OS: Windows 10
 - Version or branch: 2.9.1 + 2.10 Alpha ([up to Actions Build #417](https://github.com/AttorneyOnline/AO2-Client/actions/runs/1814131487))

Note: Issue was not present in 2.9.0, or any 2.9.1 RC builds. Issue first present in [2.9.1 Homebrew](https://github.com/AttorneyOnline/AO2-Client/releases/tag/2.9.1-cw1).

Issue was first documented (by me) in Official AO Discord's [#bugs channel](https://discord.com/channels/278529040497770496/353369729328611330/838854026317529138) (Message link hyperlinked, in1tiate made a comment about aoimage masking a little further down. Might be worth looking into?)

**Comment by oldmud0** [comment]
Pretty sure this was intended behavior for some reason

**Comment by Crystalwarrior** [comment]
> Pretty sure this was intended behavior for some reason

yeah the intended behavior sucks

**Comment by oldmud0** [comment]
It's a pretty fast operation. It uses architecture intrinsics from what I remember. Hmm maybe we'll need a config option for masking.

**Comment by Crystalwarrior** [comment]
@oldmud0 make it a theme option

**Comment by oldmud0** [comment]
K
