### ISSUE TITLE
Unable to Select Subtheme from a Mounted Base Folder

### ISSUE THREAD

**Issue by Crystal2002** [AttorneyOnline/AO2-Client#641]
**Describe the bug**
When selecting a theme from a mounted base folder, the client is unable to detect any subthemes. Any themes from the "Original" base folder will display their subthemes, however.

**To reproduce**
1) Go into Settings
2) Add a Base folder
3) Save Settings
4) Close Settings
5) Open Settings again
6) Try to choose a theme from the new Base folder
7) Try to select a subtheme
8) You're given only "default" and "server" even when a subtheme exists

**Expected behavior**
The client should be able to detect the subthemes after Step 5

**Screenshots**
There should be a "Blue" option here.
![image](https://user-images.githubusercontent.com/27789584/153683266-c26a1352-dde8-4c5b-96dd-e0db3e7b6f25.png)

**Version:**
 - OS: Windows 10
 - Version or branch: 2.10 Alpha ([Actions Build #417](https://github.com/AttorneyOnline/AO2-Client/actions/runs/1814131487))

Example themes:
[AO HD 1080](https://cdn.discordapp.com/attachments/646487005303144458/941836008343891978/AOHD1080.7z)
[DR-DiamondDangit](https://cdn.discordapp.com/attachments/646487005303144458/941836594963439697/DR-DiamondDangit.7z)

AO HD 1080 should have an additional "Dark" option
DR-DiamondDangit should have an additional "Blue" option

**Comment by oldmud0** [comment]
Oh yeah pretty sure I forgot to enumerate folders correctly here. Need to resolve the path of the theme folder to scan for subthemes instead of using the default base folder
