### ISSUE TITLE
Background's design.ini should allow to over ride bg/overlay pairs

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#642]
**Is your feature request related to a problem? Please describe.**
If you have a bg folder with a lot of bgs, and you want each bg to have a simple darkness overlay, the current method is to copy-paste the same image across all the pos. This is incredibly tedious and file size inefficient.
![](https://media.discordapp.net/attachments/473197723386904577/942236231167774780/56a15c26f7cd6fb9dc59b758d0326aa9.png)

**Describe the solution you'd like**
In design.ini (which we already have due to scaling support) you should be able to define `bg_name = overlay_name` path. The _overlay naming convention does not have to be respected. 

**Describe alternatives you've considered**
The only viable alternative is copy pasting the same bg over and over. Witness testimony indicator is an option, but it relies on everyone having the same theme.

**Comment by oldmud0** [comment]
So
```ini
[Overlays]
bg_name = overlay_name
```
Okay can get behind this
