### ISSUE TITLE
Modify character select screen for joined users

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#644]
**Is your feature request related to a problem? Please describe.**
Servers should be able to send the character select screen packet to users who are already joined, meaning your list of choosable characters can change without having to rejoin the server. 

**Describe the solution you'd like**
The packet is changed to be functional when received even after courtroom is constructed. It wipes the current css, and loads the newly received one. Optionally, it can be threaded to reduce lag.

**Describe alternatives you've considered**
Rejoining sucks

**Comment by oldmud0** [comment]
If you send a new char list to the client unsolicited, it should "just work" and update the list. If not that is a bug.

**Comment by Crystalwarrior** [comment]
@oldmud0 doesn't work on 2.9.1 :/

**Comment by oldmud0** [comment]
Oh that's dumb why does courtroom_loaded mean that? Too similar to courtroom_constructed. Wonder what happens if you delete that clause
