### ISSUE TITLE
Version number is not added to exe details

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#650]
**Describe the bug**
![image](https://user-images.githubusercontent.com/3470436/154139817-405bf9b2-62bd-47de-871d-5fbbf0adb2f3.png)

**To reproduce**
1. Right-click .exe
2. Click on "Details"
3. see missing version number

**Expected behavior**
Version number is displayed in details and on tooltip

**Version:**
 - OS: Windows 10
 - Version or branch: master

**Comment by oldmud0** [comment]
I fixed this in the lawn chair but I need to copy the cmake lines to the client

**Comment by Salanto** [comment]
Version number is set in the latest CI actions : 
![image](https://user-images.githubusercontent.com/62221668/179361496-69c2f217-3276-48e2-bf5e-6b0a7881fa47.png)
