### ISSUE TITLE
Include alias argument in music packet

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#652]
**Is your feature request related to a problem? Please describe.**
When using music streams, if you implement aliases server side, they will appear as missing tracks to the end user. 

**Describe the solution you'd like**
Alias will be used to show in the music list, while main file is what will be sent when double clicked. If file is a stream, it'll be considered valid.

**Comment by Crystalwarrior** [comment]
For backwards compatibility, alias has to be the last argument of the music packet so clients that don't handle it won't freak out

**Comment by in1tiate** [comment]
A packet expansion of this nature was denied in https://github.com/AttorneyOnline/AO2-Client/pull/546. I'm voting nay based on that precedent.

**Comment by oldmud0** [comment]
Maybe instead of including an alias we can have a boolean that states if the entry refers to a local file (so it can be renamed and highlighted appropriately) or something else (so it is not highlighted).

**Comment by Salanto** [comment]
Given that 2.10 has WebAO assisted backup streaming I would argue that marking stuff as missing might be redundant these days as there is a lot of sources it can pull from to get the content itself.

**Comment by HolyMan-17** [comment]
I honestly don't see the point on this and seems to be more trouble than it's worth, given that this would require a packet expansion for something that is, honestly, already a pain to read and hell itself to work with. 

Even if the users won't care about how it's implemented, the developers' eyes will most certainly care.

**Comment by Crystalwarrior** [comment]
In that case, maybe remove the missing song notice?

**Comment by Crystalwarrior** [comment]
> In that case, maybe remove the missing song notice? And only keep the color for categories

Oh btw I meant to keep the missing song notice in the music name box, but remove the missing song color that is file based lol

**Comment by Salanto** [comment]
Literally what this handsome person implicated in here : 
![image](https://user-images.githubusercontent.com/62221668/155034436-be45db04-e62a-4de9-844e-e4db742978ee.png)

**Comment by Crystalwarrior** [comment]
yeah I got weirded out you down voted me cuz I was agreeing with you

**Comment by Salanto** [comment]
Closed after talking with CW

**Comment by oldmud0** [comment]
what was the resolution?
