### ISSUE TITLE
FrameSFX of paired partners continues to play offscreen.

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#66]
Likely the paired partner not having its sound thread killed. Will be killed if another pair requires their FrameSFX to be played, however.
Potentially what #63 (closed) is referring to, rather than the [SoundL] tag.

(https://gitlab.com/AttorneyOnline/AO2-Client/issues/66)

**Comment by Crystalwarrior** [comment]
Does this still occur in 2.8?

**Comment by Crystalwarrior** [comment]
:|

**Comment by scatterflower** [comment]
could not reproduce, seems to be fixed
