### ISSUE TITLE
Language does not update until close

### ISSUE THREAD

**Issue by Crystal2002** [AttorneyOnline/AO2-Client#662]
**Describe the bug**
When changing language, the translation strings do not update until after the client closes and is re-opened.

**To reproduce**
1. Go to Settings
2. Change your language (German, Spanish, whatever)
3. Save Settings.
4. Close Settings
5. No Language Update

(Additionally, joining a server or reloading the theme does NOT update the language)

**Expected behavior**
At bare minimum, reloading the theme or joining a server should update the language strings. Or even just a popup upon language-swap saying "Hey, we'll need to restart the client to put this into effect, do you want to do that now?" would be nice (but then you run into the use-case of trying to change languages while connected a server, which might then result in having to maybe implement being able to "snap back" to what you were doing or smth).

**Version:**
 - OS: Windows 10
 - Version or branch: [Actions Build #433](https://github.com/AttorneyOnline/AO2-Client/actions/runs/1866689071)

**Comment by in1tiate** [comment]
I don't actually know how feasible it is to retranslate the UI on language switch given the way we use QTranslate. A window saying the changes require restart would be good though. 

(As for "snap back" that's not even close to feasible, sorry)

**Comment by oldmud0** [comment]
Qt doesn't support this feature out of the box. To retranslate all widgets requires walking through all open windows and all widgets and setting their text again. This is a "nice to have" but would be rather tedious to implement.
