### ISSUE TITLE
Soundlists in Mounted Folders do not populate SFX Dropdown

### ISSUE THREAD

**Issue by Crystal2002** [AttorneyOnline/AO2-Client#670]
**Describe the bug**
Currently, the client ignores any soundlist within mounted folders, both the "global" soundlist and character-specific soundlists.

**To reproduce**
1. Add a populated sounds.ini to a character found outside of the default Base folder
2. Join a server
3. Try to select from the SFX dropdown

**Expected behavior**
Ideally, all related sounds/soundlists should be appended to the dropdown (bonus if duplicate entries can be ignored).

**Screenshots**
![image](https://user-images.githubusercontent.com/27789584/155168685-d5563e60-0f9a-4ff4-bd6b-83a4a59a2012.png)
Corresponding Sounds.ini
![image](https://user-images.githubusercontent.com/27789584/155168605-ef894e9b-5252-4865-b8ef-770b4252df23.png)

**Version:**
 - OS: Windows 10
 - Version or branch: Actions Build [#440](https://github.com/AttorneyOnline/AO2-Client/actions/runs/1868984568) & [#453](https://github.com/AttorneyOnline/AO2-Client/actions/runs/1874334926)

**Comment by oldmud0** [comment]
Seems like iniswaps.ini and soundlist.ini are not using vpaths. It is not clear to my why this is so.
