### ISSUE TITLE
Feature Request: different colored IC name on own message

### ISSUE THREAD

**Issue by FuryMcFlurry** [AttorneyOnline/AO2-Client#671]
When roleplaying and scrolling through the logs, its hard to keep track of whenever you spoke, or when others.

(Screenshot taken from DRO client.)
![image](https://user-images.githubusercontent.com/8770071/155208249-48c366e1-5e2a-4977-83e0-8887cf3523c5.png)

In the DRO client this feature already exists.

Inside of the courtroom_fonts.ini this line would color the text of their own message. `ic_chatlog_selfname_color = 119,78,156`

**Comment by Crystalwarrior** [comment]
The code for it in DRO-Client is here:
https://github.com/Chrezm/DRO-Client/blob/master/src/courtroom.cpp#L1101-L1103
