### ISSUE TITLE
Trim FL packet and raise minimum AO2-Client Version to 2.8.5

### ISSUE THREAD

**Issue by Salanto** [AttorneyOnline/AO2-Client#673]
**Describe the issue**
The FL packet is a representation of additions to the AO2, partially due to a lack of proper versioning ala Semver, and simply due to the open-source nature of the AO2-Client, causing forks and custom clients to spruce up over the years and ending up being merged into the "Vanilla" client.

Currently, every server has to send all FL features to have the current released client, 2.9.1 (or 2.10 depending on who you ask), be fully functional. While this is the simplest solution without having to worry about versions, this also has the issue that this packet has become cluttered with things most people now would consider to be standard, skewing the perceived playable version and the actual minimal version of AO2.

To address this issue the FL packets needs to be trimmed and have things that are now "standard" be removed and coded as expected to bring FL in line with the actual minimum version, which is closer to 2.8.5 as opposed to the FL packet suggesting the minimal version is 2.1.0

Here's how it could be done :
Step 1: Remove all FL entries older than 2.8.5
Step 2: Change the code to enable the features by default.
Step 3: Make sure the client doesn't crash on any server on master, excluding non-Tsu3/Akashi derivaties or severely outdated ones. 
Step 4: Seal the deal and name the minimal version on the network documentation

Additionally, it would make sense to make a general rule about the FL packet, while it still exists in the network protocol, to prevent this issue from cropping up again.

A baseline rule should be that a feature if left unchallenged for at least 1 major and 1 minor release, should be added to the minimum requirement and the minimum version number should be updated.
This also ensures that overly outdated servers and clients are slowly phased out of the userbase, as we otherwise end up bending over and backwards with excessive legacy considerations.

This change is majority housekeeping and should not affect the functionality of any client or server, as servers are still free to implement FL with legacy support present.  To note is that a server, shall it opt to trim its FL packet to be on network-parity with 2.10, would cause features to be unavailable on older clients that rely on those features being sent in the FL packet.

**Comment by stonedDiscord** [comment]
AOV ist still on 2.7 tho

**Comment by Salanto** [comment]
This issue is dead and I couldn't care less about servers which don't update their client.
The entire concept of FL is wack and needs reconsideration.
