### ISSUE TITLE
buttonX_on overlay from Characters folder

### ISSUE THREAD

**Issue by Crystal2002** [AttorneyOnline/AO2-Client#676]
**Is your feature request related to a problem? Please describe.**
Kind of an add-on from my last request ([#675](https://github.com/AttorneyOnline/AO2-Client/issues/675)), but separate issue for being self-contained. 

Another part of how DRO 1.0.x handles it's `buttonX_on` overlays is by allowing content creators to add `selected.png` to `base\characters\[character folder]\emotions`, and the final result is rendered on top of `buttonX_off` instead of being saved as a new file for indefinite use. If the client does not find this file, then it falls back to the theme.

**Describe the solution you'd like**
Parity to DRO's handling of the files, as explained above.

**Describe alternatives you've considered**

**Additional context**
Screenshot of an example folder that uses this (from DRO)
![image](https://user-images.githubusercontent.com/27789584/155405657-7443fded-88d1-4cff-96af-103d01582dc4.png)

**Comment by Crystalwarrior** [comment]
this is actually a really elegant solution to reduce the button hell and introduce more consistency

**Comment by oldmud0** [comment]
Yeah, I frankly don't remember why this solution hadn't been implemented. I think it was because I wanted to let Cents get a feature in even if it was completely brainless (sorry cents).

**Comment by Crystalwarrior** [comment]
We're gonna do https://github.com/AttorneyOnline/AO2-Client/issues/675
