### ISSUE TITLE
Font outlines

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#677]
**Is your feature request related to a problem? Please describe.**
A basic option to have an outline to text fonts

**Describe the solution you'd like**
courtroom_fonts.ini option to give outlines to fonts

**Describe alternatives you've considered**
no other solutions I can think of currently

**Comment by oldmud0** [comment]
Remember that font outline mess where the stroke gets rendered on top of the text?

Are we going to do it for real?

**Comment by Crystalwarrior** [comment]
Let's do the messy way first so at least text can be readable without a text background
We can do the for real method after

**Comment by Crystalwarrior** [comment]
Honestly fair enough, I don't have the free time to crack this but I think @chrezm figured something out that works. The problem is optimizing it to not cause lag

**Comment by Chrezm** [comment]
Correct, but I have not really pursued it further than what we've discussed in DMs beforehand.

**Comment by Izakaro** [comment]
Yes
