### ISSUE TITLE
Selecting "Spectator" on the character select screen does not send CC packet

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#689]
Change Character packet is not sent to the server when selecting "Spectator". This is bad if the server doesn't assign spectator char_id until a character is selected.

**Comment by oldmud0** [comment]
Thought we had made it send -1. Guess not.

**Comment by Crystalwarrior** [comment]
That's weird, looking through the code it apparently tries to send -1.

**Comment by Salanto** [comment]
Akashi spectator detection uses the CC packet, which works perfectly fine on the current master.
We should close this if this is not reproducible anymore.
