### ISSUE TITLE
If you select the same line on favourites as you do on public servers list, it won't register it as a new click, despite clicking on something new.

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/AO2-Client#690]
**Describe the bug**
It's hard to properly explain this and it's really trivial too, but I figured it's worth mentioning. In simple terms, if you select an entry in your favourites, then try to select the same numbered entry in the public servers list, it won't display the information for the server on the public servers list.

**To reproduce**
1. Open client
2. Go to Favourites
3. Select 0 Default local server
4. Go to Public Servers
5. Select 0 AO Official Unofficial Server (Vanilla) (or whatever the 0th entry is)
6. It won't pop up with anything new, despite Vanilla having a server description, and typically being online to give you a playercount.

Worth noting that selecting a different server and then selecting Vanilla again, or whatever is in the 0th spot, will make it work again. Likewise, if you select whatever is in the 1st spot in favourites, and then whatever is in the 1st spot in public servers, you get the same behaviour.

**Expected behavior**
The expected outcome is that it would show the server description and playercount.

**Screenshots**
![image](https://user-images.githubusercontent.com/30537683/158006307-8d296dc3-95c0-4d38-95a5-fddddcc61ba5.png)

**Version:**
 - OS: Windows 10
 - Version or branch: master

**Additional context**
It doesn't work the other way. Selecting the 0th entry on public servers and then selecting the 0th entry on favourites has it behave as you'd expect.

**Comment by oldmud0** [comment]
Thought we fixed this. Seems like it's the same stuff that breaks over and over.
