### ISSUE TITLE
Occasional Infininte SFX Loop

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#70]
In rare cases, all sound effects will loop endlessly, lagging the client and causing intense earrape.
This can only be fixed by restarting the client.
Unknown cause.

(Jumbles, https://gitlab.com/AttorneyOnline/AO2-Client/issues/70)

**Comment by Crystalwarrior** [comment]
Any cases of this occuring in 2.8?

**Comment by oldmud0** [comment]
Unknown cause and no subsequent reports.
