### ISSUE TITLE
Formatting & color-coding for debug log

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#706]
this is really ugly
![image](https://user-images.githubusercontent.com/32779090/160251218-8fe69450-da2f-4114-bc06-4cd9ef82f2c3.png)

we should make it prettier

**Comment by oldmud0** [comment]
already implemented, might be missing some theme changes
![already there](https://media.discordapp.net/attachments/323377366997008394/924467396813680700/unknown.png)

**Comment by in1tiate** [comment]
i was indeed missing theme changes
