### ISSUE TITLE
Expanded Desk Mods don't seem to be functional

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#709]
**Describe the bug**
Desk mods 2,3,4,5 are not functioning. Tested on KFO-Server which has expanded_desk_mods feature flag set.

2: desk is hidden during preanim, shown when it ends
3: desk is shown during preanim, hidden when it ends
4: desk is hidden during preanim, character is centered and pairing is ignored, when it ends desk is shown and pairing is restored
5: desk is shown during preanim, when it ends character is centered and pairing is ignored

**To reproduce**
1. Go on KFO-Server
2. Edit your char.ini to have desk mods 2,3,4,5
3. Use a preanim emote with that deskmod
4. Desk is still shown regardless

**Expected behavior**
Desk mods work as promised

**Version:**
 - OS: Windows 10
 - Version or branch: master

**Comment by Crystalwarrior** [comment]
For the record kfo server validation seems to be updated to support it
https://github.com/Crystalwarrior/KFO-Server/blob/c95fdbc4722075b443da87b8a3108b4bf9c259f3/server/network/aoprotocol.py#L701

**Comment by in1tiate** [comment]
Works on Akashi. Please test this again with current `master` branch and reopen only if this can be confirmed a client issue.
