### ISSUE TITLE
 Inconsistent Disappearing During Interjections 

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#73]
While pairing, only one of the paired clients will have their character disappear when an interjection goes off.
Potential solution: Put interjections on their own layer, rather than overwriting character emotes. This is also more accurate to AA's visual style, and allows things such as franziska's whip, or blackquill's slice to actually look right.

(Jumbles, https://gitlab.com/AttorneyOnline/AO2-Client/issues/73)

**Comment by Crystalwarrior** [comment]
Does this still occur in 2.8?

**Comment by oldmud0** [comment]
Don't think so. Didn't you put the objections on their own layer like they were supposed to?

**Comment by Crystalwarrior** [comment]
Yeah I believe so, will be closing then.

> 
> 
> Don't think so. Didn't you put the objections on their own layer like they were supposed to?
