### ISSUE TITLE
Toggle for Audio Suppression to be active or not

### ISSUE THREAD

**Issue by Crystal2002** [AttorneyOnline/AO2-Client#734]
**Is your feature request related to a problem? Please describe.**
CW recently implemented the ability for the client to be able to lower it's overall volume when it's not the program focused on. Can we get a On/Off toggle for if we want this active or not? It'd be extremely useful for those who are recording DEMO files, as right now they can't do *anything* else until after their recording is over, unless they want to have a recording with half-volume audio.

**Comment by Crystalwarrior** [comment]
You can simply put the slider at 0 or 100 depending if you want it on or off
