### ISSUE TITLE
Favorites Tab does not preserve ascii chars

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#738]
Before:
![image](https://user-images.githubusercontent.com/3470436/161654038-13e3a258-2762-487d-a190-b409b3d6138c.png)

After:
![image](https://user-images.githubusercontent.com/3470436/161654048-44a6e77e-d0f7-4e16-b04f-5da4ddc79469.png)

**Comment by oldmud0** [comment]
likely read/write to utf8 issue
