### ISSUE TITLE
When mounting base folders they should use relative paths whenever possible

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#740]
If you mount a base folder, it should attempt to create a relative path to it first. The only situation where it should use absolute paths is if `../` are required to reach the targeted folder.

This means when you mount a base folder inside of your AO folder, renaming or moving your AO folder will not break your mounts.

**Comment by Salanto** [comment]
We should probably drop this from the 2.10 milestone as path resolution currently works "good enoughTM" to not cause too many issues for now.

**Comment by Crystalwarrior** [comment]
I don't think we should drop this. First off it's tested and works, second I don't want all of your installation breaking just because you moved the ao folder somewhere

**Comment by Salanto** [comment]
There is not even a PR attached to this.

**Comment by TrickyLeifa** [comment]
Relative pathing is bad and prone to cause more issues than it solve. Use absolute file pathing.

**Comment by stonedDiscord** [comment]
how often do you rename your AO folder?

**Comment by oldmud0** [comment]
Relative pathing is useful when working with portable installations.
