### ISSUE TITLE
An option to play SFXs client-side

### ISSUE THREAD

**Issue by Satoru-1816** [AttorneyOnline/AO2-Client#746]
**Is your feature request related to a problem? Please describe.**
Most of the time you gotta guess what the SFX is going to sound like just by its name. Some of them are like "sfx-shooop", "sfx-shoomp", "sfx-thud4", "sfx-thump3", etc. Even harder if you have several variations of the same.

**Describe the solution you'd like**
A right click option on the SFX dropdown to let you play the selected sound just to yourself.

**Describe alternatives you've considered**
A small "play" button next to the dropdown to do the same thing.

**Comment by Crystalwarrior** [comment]
I wanna extend this to the music list as well and make it use your default system audio program you use

**Comment by in1tiate** [comment]
that requires writing OS-specific code to handle the different ways that operating systems might define how to open an audio file with the "default" audio program. i'd recommend just playing the sound effect in channel 5 of the sfx player, all the code's already there

**Comment by Crystalwarrior** [comment]
Oh yah fair enough
