### ISSUE TITLE
Testimony indicator overlays chatbox

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#747]
**Describe the bug**
When witness testimony is pressed, it overlays UI instead of being contained to viewport. It should be confined to the viewport instead so it appears behind the chatbox.

**Comment by in1tiate** [comment]
this is not a bug, WT/CE are part of the UI and not the character and thusly appear over the chatbox

**Comment by oldmud0** [comment]
This is highly open to debate. I would err on the side of keeping it on top of the chatbox as there may be themes that use a full-screen animation.

**Comment by Salanto** [comment]
So... issue closed?
