### ISSUE TITLE
Rapidly spamming objections occasionally causes text crawl not to appear.

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#75]
In spam-heavy areas, or if objecting under the right circumstances, the text crawl will not appear, and neither will the character or text box until the text crawl has finished. At which point, the text box/character/etc. will appear.

(Jumbles, https://gitlab.com/AttorneyOnline/AO2-Client/issues/75)

**Comment by Crystalwarrior** [comment]
I remember this happening sometimes on 2.8. Needs exact steps to reproduce though

**Comment by Crystalwarrior** [comment]
Has a reliable method of reproduction been detected?

**Comment by Crystalwarrior** [comment]
Could not reproduce in master
