### ISSUE TITLE
Default shownames not changing after iniswapping

### ISSUE THREAD

**Issue by Satoru-1816** [AttorneyOnline/AO2-Client#759]
**Describe the bug**
Default shownames specified in the char.ini are not taken into account when iniswapping to another character. E.g. if you're using Phoenix and you iniswap to Edgeworth, the showname will keep being "Phoenix" unless you manually change it in the showname box.

**To reproduce**
1. Send a message with any character
2. Iniswap and send a message again
3. See the same showname as before

**Expected behavior**
The showname should update to the iniswapped character's default showname.

**Version:**
 - OS: Windows 10
 - Version or branch: 2.9.1 and 2.10-alpha

**Comment by Crystalwarrior** [comment]
The showname will no longer display the char name and just have place holder text "Showname" as per https://github.com/AttorneyOnline/AO2-Client/pull/753

Iniswap drop down already fulfills this purpose

**Comment by Satoru-1816** [comment]
My bad, forgot to clarify that I was referring to the IC chatbox's showname
Thought that it was kinda weird that it just keeps the og character showname instead of updating it to the iniswapped character's

So is this the intended way?

https://user-images.githubusercontent.com/81326989/166249380-d1e0d92b-6ddd-4c90-a265-0b2952ccf16f.mp4

**Comment by Crystalwarrior** [comment]
Actually yeah it is intended behavior so when you iniswap it's still clear what folder you're using unless you change the showname manually
