### ISSUE TITLE
Demo playback not loading demo files

### ISSUE THREAD

**Issue by Satoru-1816** [AttorneyOnline/AO2-Client#764]
**Describe the bug**
Nothing happens when you try to load a demo in the latest builds of 2.10-alpha, keeps saying Offline and you can't press Connect. Tested it with several demo files and noticed that it still shows up an error message when using a broken pre-2.9.1 demo tho

**To reproduce**
1. Load a demo in a recent 2.10-alpha build
2. See nothing happening

**Version:**
 - OS: Windows 10
 - Version or branch: 2.10-alpha

**Additional context**
Bug starts happening since [Build #635](https://github.com/AttorneyOnline/AO2-Client/actions/runs/2096308060)

**Comment by Crystalwarrior** [comment]
Uh oh

**Comment by Salanto** [comment]
Does not happen on latest master anymore. If you are able to replicate the issue, reopen this one.
