### ISSUE TITLE
debug: Unknown property font-border Debug Log spam

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#766]
using the below theme, when you switch to the Debug view, it will spam this debug message and cause lag every time someone speaks.
`debug: Unknown property font-border`

[DR-DiamondDangit.zip](https://github.com/AttorneyOnline/AO2-Client/files/8692910/DR-DiamondDangit.zip)

**Comment by stonedDiscord** [comment]
the issue is in line 22 of courtroom_stylesheets.css
