### ISSUE TITLE
 Muted characters leak through mute if they interrupt someone else with an objection. 

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#77]
To reproduce: Mute someone, have another character post a long message.
Then have that muted person objection-interrupt the other character.

They will then have their message play as the character you didn't mute, but upon ending the idle of whatever emote the muted character used will appear.

(Jumbles, https://gitlab.com/AttorneyOnline/AO2-Client/issues/77)

**Comment by Crystalwarrior** [comment]
Does this occur in 2.8?

**Comment by Crystalwarrior** [comment]
Could not reproduce in master
