### ISSUE TITLE
 Holding enter slows the entire client. 

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#79]
Does what it says on the tin. If you're unable to send a message for whatever reason at the time, holding enter will slow the entire client down, including text crawl, currently playing animations, but not sounds.

(Jumbles, https://gitlab.com/AttorneyOnline/AO2-Client/issues/79)

**Comment by oldmud0** [comment]
This is probably something really stupid that AOTextArea is doing, like hooking to the wrong event. It should be fixed in 2.8.

**Comment by stonedDiscord** [comment]
this sounds a lot like the app dedicating all of it's cpu time to handling the enter press instead of the window events and so windows considers it to be "hanging" because it's not replying to the windows api

**Comment by Crystalwarrior** [comment]
Cannot reproduce in 2.8
