### ISSUE TITLE
Drop-down menu name sorting is not the same as windows folder name sorting.

### ISSUE THREAD

**Issue by WisoAltred** [AttorneyOnline/AO2-Client#793]
**Describe the bug**
AO's sorting method is not the same as seen in the windows folder (By name) when interacting with numbers.

**To reproduce**
1. Go to Themes/Any folder, use a folder that has a name that starts with 1-9, and another one that starts with 10/11, etc.
2. Sort by name in folder (though its the default), and look at themes drop down / whatever drop down you've allocated it to (inis work too.).
3. World shattering difference.

**Expected behavior**
AO should be able to sort the same way windows does when interacting with 1-9s and 10s. 

**Screenshots**
![unknown (1)](https://user-images.githubusercontent.com/61384316/175387080-683069e0-331e-4469-a387-c2020ee7851f.png)
![unknown3](https://user-images.githubusercontent.com/61384316/175387119-2a37c71e-016a-4f14-8a1f-68a8504155f0.png)

**Version:**
 - OS: Windows 10
 - Version or branch: 2.9.1/2.10.0 (latest)

**Additional context**
I'd imagine the way we sort was changed for some reason or another in the past due to a previous issue, but hopefully it can be improved to solve this one too.

**Comment by Salanto** [comment]
As already discussed the sorting is not really viable and plattform dependant. What might look right for windows might be incorrect for Linux, MacOS, etc

**Comment by oldmud0** [comment]
Numerical sorting is a special feature in Windows Explorer. Seems like Qt has a similar feature in the `QCollator` class: see https://stackoverflow.com/a/36018397

**Comment by Salanto** [comment]
Tried the Collator before, but didn't see the numeric sorting mode. Will try later! Thanks for pointing it out lb!
