### ISSUE TITLE
Replace libbass with FLOSS library

### ISSUE THREAD

**Issue by scatterflower** [AttorneyOnline/AO2-Client#797]
**Is your feature request related to a problem? Please describe.**
I've been trying to create reproducible distribution binaries of AO, as well as a Gentoo ebuild. The nonfree library has posed numerous issues, especially given that it is a runtime/build dependency. Furthermore, CMake does not properly check that the library is available when generating the makefile.

**Describe the solution you'd like**
Replace BASS with something like PortAudio, OpenAL, Qt's built-in audio library, etc

**Describe alternatives you've considered**
Compiling without audio works, but is not a real solution

**Additional context**
I'm willing to help rewrite the audio backend

**Comment by Salanto** [comment]
Afaik QtMultimedia fell through because it relies too heavily on the underlying OS to handle file formats, so you lose a lot of format portability.
