### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#8]
It was said in January that there was going to be a Russian version of AO. However, there are no resource files whatsoever that include Russian strings, nor is the application using the Qt translator.

**Comment by oldmud0** [comment]
More discussion here: https://gitlab.com/AttorneyOnline/AO2-Client/issues/8

**Comment by stonedDiscord** [comment]
Когда рак на горе свистнет

**Comment by stonedDiscord** [comment]
this is merged and finished
