### ISSUE TITLE
 Using /save_case without state argument crashes the client 

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#82]
**How to reproduce:**
Using a client that includes f826ba39 type `/save_case name` in the ooc chat, as soon as Enter is pressed the client will crash. Using the build from the pipeline gives
Segmentation fault as message on stderr, while compiling the client gives the message:

>ASSERT failure in QList::operator[]: "index out of range", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h, line 549

(@likeawindrammer, https://gitlab.com/AttorneyOnline/AO2-Client/issues/82)

**Comment by stonedDiscord** [comment]
why is this closed when it's not fixed yet

**Comment by stonedDiscord** [comment]
it is fixed and i didn't see it

**Comment by likeawindrammer** [comment]
The merge request isn't referenced on github, probably because of the migration. For future reference this was fixed with https://github.com/AttorneyOnline/AO2-Client/commit/b15c6f15f0b13bce4ef7305efa08c1d257401def
