### ISSUE TITLE
Allow users to disable music streaming.

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/AO2-Client#827]
With the addition of downloading from webao assets, if a user lacks a song that's in the serverfiles, the user should be able to say that they don't want to download the song and just have it not play. Maybe they have music muted. Maybe they don't want random downloads. Maybe they just hate the song, hence it being missing in the first place. Doesn't really matter. The option should just exist if we're going to this extent with it.

This should also extend to regular streaming where someone does /play funnydiscordlinkmp3. Maybe I don't want to download and hear funny song that the mod played for the 20th time.

To be specific, a simple checkbox that says Download Songs and disabling it would stop all (future) music streaming from happening would be great.

**Comment by oldmud0** [comment]
thought we already had an issue for this? Honestly don't know why this option doesn't exist yet.
