### ISSUE TITLE
Remove demo server entry from favorite server list

### ISSUE THREAD

**Issue by TrickyLeifa** [AttorneyOnline/AO2-Client#834]
**Is your feature request related to a problem? Please describe.**
The demo server is in a dumb location; it shouldn't be in the favorite server listing. This also comes as a double problem: simply clicking on the demo server entry will open up the demo server widget! Why??

**Describe the solution you'd like**
It should be a different button altogether that you have to press in other to activate the demo server mode.

**Describe alternatives you've considered**
None.

**Additional context**
This would also get rid of needless complexity associated with code of the server listing.

**Comment by stonedDiscord** [comment]
i think the favorites is a good place for it

**Comment by oldmud0** [comment]
option 1: split server list into 3 tabs
![image](https://user-images.githubusercontent.com/5247009/182008556-2df18891-068a-4196-a9a6-51bb62536f96.png)

option 2: change settings button into icon and add demo playback button alongside it
![image](https://user-images.githubusercontent.com/5247009/182008622-88ccbbbc-6b71-4fcf-95cd-a604f33ef818.png)

did I mention modernizing the darn lobby screen so it doesn't look like it's from 2005? oh yeah that too

**Comment by Salanto** [comment]
The split would likely make the most sense as option 2 breaks established behaviour on how to "enter" a server, even if demos are not real servers.

**Comment by TrickyLeifa** [comment]
But what's wrong with 2 different kind of textures and one untextured button anyway?

It adds to the flavor.
