### ISSUE TITLE
People can play music through SFX paths.

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#84]
By pointing to a music file through ini-editing, anyone can supply their emote with music instead of the usual sfx, and with the addition of looping and layered SFX this allows for horrible music spam abuse.

(@Parazoid, https://gitlab.com/AttorneyOnline/AO2-Client/issues/65)

**Comment by stonedDiscord** [comment]
sounds like a feature

**Comment by oldmud0** [comment]
At this point, basically any quirk in the client is.

**Comment by Crystalwarrior** [comment]
Can be enforced from the server side tbf.

**Comment by oldmud0** [comment]
There is a convincing case indeed to enforce this on the server side.

**Comment by Crystalwarrior** [comment]
ye so let servers enforce it on the serverside lol
