### ISSUE TITLE
Pair, mute lists go under other widgets

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#852]
**Describe the bug**
Pair, mute lists go under emotes and other widgets making it hard to click

**To reproduce**
1. Go to KFO 2x Theme
2. Click on "Pairing" button
3. See list under emotes

**Expected behavior**
Pair, mute lists are over the emotes

**Screenshots**
![image](https://user-images.githubusercontent.com/3470436/183309880-0c020c9f-8e2e-45a1-bf3e-7bd933bb9c9a.png)

**Version:**
 - OS: Windows 10
 - Version or branch: [2.10rc1](https://github.com/AttorneyOnline/AO2-Client/releases/tag/2.10rc1)

**Additional context**
could solve by just calling [raise()](https://doc.qt.io/qt-6/qwidget.html#raise) on list widget creation

**Comment by Salanto** [comment]
(That is not a solution, that is a workaround.)

**Comment by oldmud0** [comment]
huh i thought the lists had always gone on top not below?

that sounds like a regression

**Comment by Salanto** [comment]
It's an order issue. Someone moved code under the list, causing it to drop below them. Another glorious display of AOs courtroom being a hacked-together mess at this point.
