### ISSUE TITLE
Servers with large character rosters have some characters not appear on the first page.

### ISSUE THREAD

**Issue by ghost** [AttorneyOnline/AO2-Client#854]
Upon connecting to a server that has a massive character roster, some of the characters on the roster doesn't appear on the first page. This is fixed by moving to the next page of characters, then returning back to the first page.

**Evidence:**
Upon connecting to server: 
![image](https://user-images.githubusercontent.com/86204624/184028856-7a8773cc-e09a-475f-b670-3813245d1dd7.png)
After refreshing via going to next page then back to first page:
![image](https://user-images.githubusercontent.com/86204624/184028916-cc307c2e-99e6-4107-9936-07eaefbe7f86.png)

**To reproduce:**
1. Open up the release candidate version of AO 2.10 and connect to a server with a large roster. (Case Cafe, Mountain of Spirits, and Killing Fever Online as good examples for servers with large rosters)

**Expected behavior**
Behavior should be what was described on first paragraph if steps are done correctly.

 OS: Windows 11
 Version : 2.10 RC 1

**Comment by oldmud0** [comment]
Does it always only show the first 90?

**Comment by Jouto44** [comment]
> Does it always only show the first 90?

Yes, whenever you connect to a server with a large roster, it will always show the first 90 upon being connect. This problem usually goes away when "refreshing" the first page via going to the next page of characters and going back to the first page.

**Comment by Salanto** [comment]
Yeah, you can reproduce it very easily on CaseCafe.
