### ISSUE TITLE
Improve HDID calculation on Linux

### ISSUE THREAD

**Issue by scatterflower** [AttorneyOnline/AO2-Client#856]
Currently, the first uncommented line from /etc/fstab is read and searched for a "UUID=" portion. Not only is this very brittle, as it does not work properly for systems which use block device filenames rather than UUIDs, it is also very prone to manipulation; changing the ID on Linux is as simple as adding a bogus entry to the fstab.

There are myriad better ways to improve this system. The biggest challenge is arguably determining which filesystem is fixed and can be used to uniquely identify the solution; the trivial, and likely best solution is to choose the root partition. However, it is worth noting, that the root partition does not necessarily have to be backed by a physical block device, and may not be the best way to identify a computer uniquely.

That said, determining the UUID of the root partition is likely the most effective parallel to the Windows method. This is liable to change upon re-installing the OS, but it is less brittle than the current solution. A `system()` call to the `mount` utility, or parsing the fstab, can both determine the block device (and trivially the UUID) of the root partition.

Another approach would be to use another source of information to determine a unique fingerprint. A few examples may be:

### /etc/machine-id
This file is created by all distros that I am aware of at install time. It is very simple to read and does not change. However, a savvy user can easily edit this file, and it is not persistent between installations.

### Network adapter HWAddrs
These are tied to hardware, but once again, a savvy user can change this, and may not be as unique as is needed for these purposes

### Hash of enumerated hardware data (e.g. lspci)
This data is largely static and difficult to change without modifying the configuration of the hardware, however, any given setup has a distinct change of lacking uniqueness. Furthermore, simple hardware changes may invalidate the fingerprint.

These are just a few ideas off of the top of my head, and I hope that more can be discussed in this issue. Furthermore, I think all of these proposals are flawed in one way or another, but make no mistake: the current system is too error-prone to remain in use, and I think any of these would be an improvement. My personal choice is /etc/machine-id, but I'd love to see some discussion on this topic.

**Comment by stonedDiscord** [comment]
My vote is for /etc/machine-id
lspci is a bad idea, it changes when i plug in an NVMe SSD

**Comment by Salanto** [comment]
Does Linux store anywhere when the file was last modified/created. If its never changed unless a user tampers with it, we could realise some baseline protection that way?

**Comment by oldmud0** [comment]
nice essay.

however

[`QSysInfo::machineUniqueId`](https://doc.qt.io/qt-6/qsysinfo.html#machineUniqueId) ([source](https://code.woboq.org/qt5/qtbase/src/corelib/global/qglobal.cpp.html#_ZN8QSysInfo15machineUniqueIdEv))

it uses `/usr/local/var/lib/dbus/machine-id` and then `/var/lib/dbus/machine-id`. you can recreate the machine id but it requires a restart. but if you've reached that point in your intellectual development, you are probably not doing hdid evasion

**Comment by sus-impost0r** [comment]
It doesn't matter too much because any savvy user -- especially the ones on Linux -- will just patch out the HDID code in client.

> `popen`ing `mount`

`mount` can easily be replaced by the user:
`PATH=/path/to/directory/with/user-defined-mount AO2-Client`

> last modified / created time

`ctime` and `mtime` are both user-modifiable, though harder to modify. 

> `QSysInfo::machineUniqueId` (`/usr/local/var/lib/dbus/machine-id`)

This seems like the best option so far, but it relies on D-Bus. This shouldn't be an issue with most desktop environments, but it might become one.
There should be a fallback that isn't returning the empty string if `machineUniqueId` fails.

**Comment by sus-impost0r** [comment]
> you can recreate the machine id but it requires a restart.
I can't verify that. I was able to easily change the contents of `/var/lib/dbus/machine-id` on my machine, without restarting.

**Comment by TheTechRobo** [comment]
> Does Linux store anywhere when the file was last modified/created. If its never changed unless a user tampers with it, we could realise some baseline protection that way?

That's part of the general file metadata, but can be fairly easily manipulated ([touch(1)](https://www.man7.org/linux/man-pages/man1/touch.1.html)
