### ISSUE TITLE
Background does not update till an MS packet is received.

### ISSUE THREAD

**Issue by AwesomeAim** [AttorneyOnline/AO2-Client#862]
aka Display Changed Backgrounds Immediately but this title makes it sound like I know what I'm talking about

When the background is changed, we know and acknowledge that it did (and even change the previews in the position dropdown) but don't update the viewport to reflect the changed background until someone says something. It'll also be blank upon joining a server until someone says something.

Web actually got this right, and shows the background immediately, while KFO-Server sends the pos so that it displays the changed BG immediately for client users, which, while a hack resolution, does imply that this is desirable behaviour.

**Comment by in1tiate** [comment]
I do not consider this behavior desirable unless there is no message currently being displayed onscreen. Messages are immutable, which should include scene elements such as background and position. Changing them on the fly goes against the contained nature of AO's message protocol.

**Comment by oldmud0** [comment]
This was introduced intentionally in 4f738bfe34695db745d251e9461823b8835de201 as part of the KFO merge. @Crystalwarrior could you explain the context of this change?

**Comment by in1tiate** [comment]
given it has been over a year without input i am closing this issue
