### ISSUE TITLE
"Under" option for layers in effects.ini doesn't work

### ISSUE THREAD

**Issue by Yakkak** [AttorneyOnline/AO2-Client#875]
**Describe the bug**
The option for layers called 'under', as described in the comments of the effects.ini, does not actually place the effect underneath the character as described. It instead overlays it ontop of _everything_, including the chat itself, much like how the 'chat' option works.

**To reproduce**
1. Head into a testing environment
2. Open up the effects.ini
3. Change the 'Impact' layer's setting to 'under'.
4. Save.
5. Play the effect.

**Expected behavior**
It should do as the name imply, and place the effect directly behind the character sprite.

**Version:**
 - OS: Windows 10
 - Version or branch: 2.10.0

**Additional context**
Even when exiting and re-entering the testing environment, and reloading the theme, it remains consistently broken.

**Comment by Salanto** [comment]
Reason: The author seems to have changed their mind during development and incorrectly documented under, while the key in the code used is "behind"

**Comment by Salanto** [comment]
Not a client issue in the end, but a documentation one. Closing.
