### ISSUE TITLE
Lobby shows more players than in courtroom for Vanilla.

### ISSUE THREAD

**Issue by Jouto44** [AttorneyOnline/AO2-Client#878]
The lobby in AO seems to show more players in Vanilla than the actual amount of players.

Lobby:
![image](https://user-images.githubusercontent.com/86204624/198337669-2ca0537a-26d8-4664-af8e-3c49b3e14d4e.png)

In Court:
![image](https://user-images.githubusercontent.com/86204624/198337699-c16a2c9b-467c-4fee-b19b-b1d29100a2d4.png)

1. Check the player amount in AO for Vanilla.
2. To in court and use /getareas to get the amount of players in Vanilla

If the player count for Vanilla is different from lobby and in court, than the bug is still active.

OS: Windows 11
Version: 2.10

**Comment by Salanto** [comment]
That data is send by the server..this is at best an accounting issue on TsuKFO
