### ISSUE TITLE
Save last audio volume instead of setting a default in settings

### ISSUE THREAD

**Issue by Salanto** [AttorneyOnline/AO2-Client#892]
Right now AO2's volume in the settings is the clients default volume when joining a server. While running changes are made in the mixer.

This creates several issues: 
- Many users are unaware that the audio settings in the menu/config are the default join volumes and wonder why their audio volumes from mixer don't carry over to the enxt time they open the client.
- It works different than WebAO, which saves your last audio settings and restores them when reopening it
- It is extremely counter-intuitive to be able to change a setting which does nothing until you rejoin a server.

A solution would be to remove the default audio volume behaviour and just save the last set volume from mixer/settings, allowing both to change volume and restore them from settings for a consistent experience.

**Comment by stonedDiscord** [comment]
web parity issue :omegalol:

**Comment by Salanto** [comment]
:omgparityissue: 😱 😱
