### ISSUE TITLE
Zoom speedlines splash layer is not scaled by default

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#895]
The zoom speedlines (`defense_speedlines` and `prosecution_speedlines`) look weird on themes with a bigger viewport than expected, causing the speedlines to fail to cover the entire background. This can be resolved on the user end by creating an .ini file with a `stretch=true` override, however the lack of default stretching is odd regardless.

![image](https://user-images.githubusercontent.com/3470436/222808559-33abe796-8b97-4312-b497-772294bf637b.png)

**Version:**
 - OS: Windows 10
 - Version or branch: master

**Comment by in1tiate** [comment]
there are so many things wrong with this image

**Comment by Salanto** [comment]
The fact default effects even rely on the effects.ini system is utterly terrible.
