### ISSUE TITLE
Character names converted to lowercase

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#9]
This causes all characters to fail to load on non-Windows builds.

**Comment by oldmud0** [comment]
Culprits:
https://github.com/AttorneyOnline/AO2-Client/blob/a14da4c5415dfd711c59eef1f840429393218cf1/path_functions.cpp#L56
https://github.com/AttorneyOnline/AO2-Client/blob/a14da4c5415dfd711c59eef1f840429393218cf1/path_functions.cpp#L66
https://github.com/AttorneyOnline/AO2-Client/blob/a14da4c5415dfd711c59eef1f840429393218cf1/path_functions.cpp#L86
Basically everywhere where `toLower` is being used.

**Comment by stonedDiscord** [comment]
using the capitalization from user input will probably break too

**Comment by oldmud0** [comment]
Where are lowercase char names used?

**Comment by OmniTroid** [comment]
The reason for this is exactly because AO is largely used on windows, there's 0 consistency in any capitalization whatsoever. The idea is that the content for linux builds is delivered in all lowercase w/ instructions to extract future content in all lowercase. Mac's filesystem is case insensitive iirc

**Comment by oldmud0** [comment]
The solution to this problem is not trivial. I would need to scan the directory and glob it case-insensitively to find the desired resource. But I have no plans to make major modifications like this to the AO2 code base - sorry.

**Comment by MD-ThorErik** [comment]
It would be better to make resource names case-sensitive to begin with...

**Comment by oldmud0** [comment]
Some asset authors have taken the liberty of using whatever case they want - you will find some character folders with SFX names such as `TakeThat.wav` instead of `takethat.wav`, or a directory named `Emotions` instead of `emotions`.

**Comment by OmniTroid** [comment]
when adding file updates, go into base dir(or directory above, depending on how the update is structured)

for .rar updates
rar x -cl the_worst_update.rar

for .zip updates
unzip -LL the_worst_update.zip

for (the unlikely event of) .tar updates
tar --transform 's/.*/\L&/' -xvf the_worst_update.tar

in most cases it'd make sense to add force overwrite flags as well:
rar: -o+
unzip: -of
tar: --overwrite

see how that works out for you

**Comment by gameboyprinter** [comment]
This is addressed in PR #34
