### ISSUE TITLE
List dependencies for Linux

### ISSUE THREAD

**Issue by lambdcalculus** [AttorneyOnline/AO2-Client#900]
On Windows, AO packs all of Qt that is necessary for AO to function into DLLs.

On Linux, though, the user is expected to have all the necessary parts installed in their system. With no dependency list, sometimes we're left guessing what exactly it is we have to install.

A dependency list would also enable users (or the developers if they so wish) to package AO for different distros, making the installation process smoother.

**Comment by stonedDiscord** [comment]
Qt5 and BASS are both listed in the project readme

**Comment by lambdcalculus** [comment]
On Arch, I was able to identify the following dependencies:
* `qt5-base`
* `qt5-websockets`
* `qt5-imageformats`
AO also loads `libQt5Pdf.so.5` and `libQt5Svg.so.5`, owned by `qt5-webengine` and `qt5-svg`, but I've never really seen SVGs on AO so I don't know if they're necessary. (And Wayland users also need `qt5-wayland`, ofc.)

On Fedora, these correspond to:
* `qt5-qtbase`
* `qt5-qtwebsockets`
* `qt5-qtimageformats`

On Ubuntu 22.04LTS, these correspond to:
* `qt5-base-dev`
* `libqt5websockets5`
* `qt5-image-formats-plugins`
Technically you can get more specific since Ubuntu splits up the necessary modules into more packages, but all the ones needed by AO are depended on by `qt5-base-dev`, so I'll leave it like this for easier correspondence.

**Comment by stonedDiscord** [comment]
do you want to write a PR for the README.md to add this?

**Comment by lambdcalculus** [comment]
Sure. To make it brief I'll just list the install commands for each distro. Should I do it under the Qt credits section or in a different part? Also, I'll include the `qt5-svg` package and variants, just in case.

**Comment by stonedDiscord** [comment]
between 

Refer to the docs


and



Credits
