### ISSUE TITLE
"Scaling" client setting broke

### ISSUE THREAD

**Issue by scramel** [AttorneyOnline/AO2-Client#916]
**Describe the bug**
The client "scaling" option in the settings menu does not work if set to "smooth". Backgrounds and chars do scale smoothly if specified in their .ini files, but if not, it always defaults to pixel scaling even if specified otherwise.

**To reproduce**
1. Make sure a char or background doesn't have scaling specified in their .ini files
2. Set the client scaling to smooth

**Expected behavior**
Assets should look pixelated instead of smooth

**Screenshots**
![image](https://github.com/AttorneyOnline/AO2-Client/assets/61172451/f85aaea8-48e5-42cf-8180-774a2e701167)

**Version:**
 - OS: Windows 10
 - Version or branch: 2.10.1

**Comment by stonedDiscord** [comment]
this should be fixed with #918 
i'm assuming you don't have Qt installed so please wait a little for the windows CI runs to work again

**Comment by lambdcalculus** [comment]
A workaround meanwhile is to set `default_scaling` to `smooth` (instead of "Smooth" or whatever else) in your `config.ini`. Though you will need to do that every time you save your settings.
