### ISSUE TITLE
Auto-GetArea(???) - Player Presence Menu

### ISSUE THREAD

**Issue by Salanto** [AttorneyOnline/AO2-Client#929]
The list needs to:
```
- Show all clients char icon, showname and whether or not they are CM in a list that does not take up over 35% of the client's realestate.
- Add any client the moment they join the area, and remove them the moment they leave.
- Be scrollable, given 10 or more players or around.
```

It should optionally: (Don't count on it.)
```
- Allow people to right click for a context menu, for regular players to mute/pair/PM, areakick (as CM), or ban (as mod).
- Be turned off based on an area's setting or some attirbuite a CM gives their multiclient.
```

**Comment by Ganty1999** [comment]
good idea but it will better in "mute/pair" (the right click thing) instead.
> Add any client the moment they join the area, and remove them the moment they leave.

did the pocket of "charscheck" becomes unused?

**Comment by Ganty1999** [comment]
> CharsCheck is not properly implemented anymore due to KFO-Server (and derivatives) allowing an overload of a charslot by multiple users (and somehow multiple off-by-one errors.). Relying on it will cause issues down-the-line. It also does not give us all relevant metadata.

we can added delay (QTimer) for avoiding QVector be overload by be called.. and keep be sync of areas users. (client-side)
> Using a dedicated packet to control the behaviour allows slightly more versatile usage and (might) help adressing issues due to differences between servers (such as Akashi and KFO-Server having different arguments for their commands.)

alright, it's there might been replacing the packet of "charscheck" instead?
