### ISSUE TITLE
Switching subthemes resets timestamp log format

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#950]
Please don't ask me why this happens. It's possible this is fixed by #949, needs testing

**Comment by lambdcalculus** [comment]
What was happening to me was that accessing the settings menu in general unset the timestamp log format in the `config.ini`, but the reset in the UI doesn't happen until you reload the theme, so this may be what is going on there.

Doesn't happen to me on #949, but I'd appreciate it if anyone else could test it.

**Comment by Salanto** [comment]
I didn't manage to reproduce it either. Closing the issue for now.
