### ISSUE TITLE
Version 2.10.1 does not run under Debian 12.5

### ISSUE THREAD

**Issue by XandrosDarkstorm** [AttorneyOnline/AO2-Client#951]
**Describe the bug**
Version 2.10.1 does not run under Debian 12.5. Previous version 2.10.0 runs perfectly fine.

**To reproduce**
1. Download latest release.
2. Run it using terminal.
3. See error: `./Attorney_Online: symbol lookup error: ./Attorney_Online: undefined symbol: _ZdlPvm, version Qt_5`

**Expected behavior**
Application should run without problems.

**Version:**
 - OS: Debian 12.5 (amd64)
 - Version or branch: 2.10.1

**Additional context**
Running `ldd` on Attorney_Online revealed that all libraries are present on my system.

**Comment by stonedDiscord** [comment]
Ubuntu has the same problem (despite AO being built on Ubuntu)
https://forum.qt.io/topic/117486/error-undefined-symbol-_zdlpvm-version-qt_5

**Comment by lambdcalculus** [comment]
Probably the pre-built libraries installed by the install-qt action don't match Debian/Ubuntu's distribution of Qt. I think the options are: make distribution-specific actions for Linux; ship the used Qt libraries along with the app (as is done on Windows); *or* make an AppImage as #908 suggests (Flatpak/Snap is also an option).

**Comment by lambdcalculus** [comment]
@XandrosDarkstorm Could you check if the build on #956 works for you? The artifact is [here](https://github.com/AttorneyOnline/AO2-Client/actions/runs/9053919062/artifacts/1495189460).

**Comment by XandrosDarkstorm** [comment]
> @XandrosDarkstorm Could you check if the build on #956 works for you? The artifact is [here](https://github.com/AttorneyOnline/AO2-Client/actions/runs/9053919062/artifacts/1495189460).

Application now starts, but fails to find to load any character, preventing to join any server.:
`Error: Could not find character (char.ini) for <character_name>`

Also it complains about inability to load APNG and QWebp plugins.
Here is a log: [log.txt](https://github.com/AttorneyOnline/AO2-Client/files/15354789/log.txt)

**Comment by lambdcalculus** [comment]
Yeah, the artifact only ships a few themes, no content. You'd need to put it where your usual AO install is for it to have characters.

Anyway, as said in the PR, you might need to move libqapng.so from the "imageformats" folder to the executable's folder for that plugin to load. As for QWebp, you should try installing the package `qt5-image-formats-plugins`.

**Comment by XandrosDarkstorm** [comment]
qt5-image-formats-plugins was already installed during the test. App doesn't see it installed in the system. Symlinking `/usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqwebp.so` into the game folder works. I suspect `main.cpp` is not loading libraries properly because something is messing with library path.

Regarding content: it seems that app fails to load characters if one or more custom content folders are missing. This probably should be a separate issue.
After i symlinked my custom content folders to the folder with new client everything started working properly.

**Comment by lambdcalculus** [comment]
I see. Copying/symlinking the QWebP plugin is also required for me, though I thought it may have been specific to my machine initially.

At this point, the plugin loading and character loading are separate issues. I'll probably open them and try to work on them another time, but if you'd like to file them too and close this one, you can go ahead.
