### ISSUE TITLE
Large/Long apng files cause hard crash

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#976]
**Describe the bug**
On AOV, we have some large 60 fps animations or cutscenes. Depending on client theme these can hard crash the client, and some very large files cause the client to choke and die partway into the animation regardless (but sooner if on something like 2x).
Not sure if this behavior is present in other file formats, have not tested.

**To reproduce**
1. Grab something like [this file](https://drive.google.com/file/d/1LlxOeBP9O2mWa89hK2bfrSwy_-hUzuVK/view?usp=sharing), or any apng file in excess of ~120mb.
2. Attempt to play it in client (on a 2x theme for extra early crashing).
3. Watch as it plays partially, then either hard crashes your client, or completely locks it up.
4. Despair.

**Expected behavior**
Long animation plays without dying of extreme death, or failure to play completely does not result in a hard crash/softlock.

**Comment by TrickyLeifa** [comment]
It crashes because you run out of memory, not because of the client bugging out.

If you want to report a bug with APNG, you should report it to the plugin's author.

I'd suggest using a format other than APNG.

**Comment by collinxchu** [comment]
I have 12GB of ram. I don't think I'm running out of RAM at all just running AO, even with a beefy file like this.
Other users with similarly powerful rigs still report issues with very large files as well.

I understand the plugin isn't designed for this, but I don't think it's an issue of my hardware. I was just hoping it could be made to fail a bit more elegantly in these edge cases.
