### ISSUE TITLE
Lingering issues with Qt audio

### ISSUE THREAD

**Issue by likeawindrammer** [AttorneyOnline/AO2-Client#99]
Starting with this commit https://github.com/AttorneyOnline/AO2-Client/commit/d4129f0225ab97c320a4a72e009d3684b50f2bd2 qtaudio is used by default on linux. Everything audio related seem to work just fine, except for two minor issues.
First the Blips slider doesn't have a gradual volumen between 1% and 100%. 0% will still mute the blips completely, but even 1% will sound just as loud as 100%.
And second the Audio device selector on settings wont display any options, the sound still work though.

Note: I confirmed these two issues where introduced in that commit. But only tested on Linux, I did not try AO with qtaudio on Windows.

---
- [x] Blips slider doesn't have a gradual volume between 1% and 100%
- [x] Audio devices are not being listed in settings

**Comment by oldmud0** [comment]
The SFX player is misconfigured and is missing a conversion to a scalar value:

https://github.com/AttorneyOnline/AO2-Client/blob/047ce046316a96c6183846b40062dd6f72de61fd/src/aosfxplayer.cpp#L97-L101

As for the audio device selector, it is currently configured to only work with BASS - if BASS is not used, then it won't work:

https://github.com/AttorneyOnline/AO2-Client/blob/047ce046316a96c6183846b40062dd6f72de61fd/src/aooptionsdialog.cpp#L234-L254

So, there's missing code there.

**Comment by likeawindrammer** [comment]
Blip slider is now working on Linux thanks to https://github.com/AttorneyOnline/AO2-Client/commit/4700902551f80769b54cb452b0fcb794669c553b

**Comment by oldmud0** [comment]
sD should embrace feature branches, but whatever.

- [x] Blips slider doesn't have a gradual volume between 1% and 100%
- [ ] Audio devices are not being listed in settings

**Comment by stonedDiscord** [comment]
it's a bugfix for an already merged branch
for the device list i will need:

https://doc.qt.io/qt-5/qsoundeffect.html#QSoundEffect-1
https://doc.qt.io/qt-5/qaudiodeviceinfo.html

**Comment by likeawindrammer** [comment]
audio devices are listed on the device list. Thank you @stonedDiscord!
